/* ScummVM - Graphic Adventure Engine
 *
 * ScummVM is the legal property of its developers, whose names
 * are too numerous to list here. Please refer to the COPYRIGHT
 * file distributed with this source distribution.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

// Generated by tools/gen_cutscenes.py of the Alien Incident reverse engineering
// repository -- do not edit by hand.
//
// The cutscenes: 14 dispatch arms, 15 records out of GAME.EXE's data
// segment, and 44 scene procedures lifted out of disasm/seg_cutscene.asm
// into 61 effects.

#include "alien/cutscenes.h"

namespace Alien {

// Every effect any scene procedure runs, in procedure order.
static const ScriptEffect kCutsceneEffects[] = {
	{ kOpAnimPlay2,      4, {     0,     1,     6,     4,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(0, 1, 6, 4)
	{ kOpUnsupported,    0, {     0,     0,     0,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_list(1, 0, 12, 3)
	{ kOpAnimPlay2,      4, {     0,     1,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(0, 1, 1, 0)
	{ kOpAnimPlay2,      4, {     1,     1,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(1, 1, 1, 0)
	{ kOpAnimPlay2,      4, {     0,     6,    14,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(0, 6, 14, 3)
	{ kOpMusic,          1, {     5,     0,     0,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// music_play_slot(5)
	{ kOpAnimPlay2,      4, {     1,     5,    22,     4,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(1, 5, 22, 4)
	{ kOpUnsupported,    0, {     0,     0,     0,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// call 13b8:0f76(140)
	{ kOpAnimPlay2,      4, {     0,     1,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(0, 1, 1, 0)
	{ kOpAnimPlay2,      4, {     1,     1,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(1, 1, 1, 0)
	{ kOpAnimPlay1,      4, {     0,     1,    63,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 1, 63, 2)
	{ kOpAnimPlay2,      4, {     0,     1,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(0, 1, 1, 0)
	{ kOpUnsupported,    0, {     0,     0,     0,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_list(0, 0, 5, 3)
	{ kOpUnsupported,    0, {     0,     0,     0,     0,     0,     0 }, 0x00, 1, { { 0xa498, 8, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_list(0, 0, 24, 3)
	{ kOpAnimPlay2,      4, {     0,     7,    26,     3,     0,     0 }, 0x00, 1, { { 0xa498, 9, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(0, 7, 26, 3)
	{ kOpAnimPlay1,      4, {     2,    12,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(2, 12, 1, 0)
	{ kOpAnimPlay2,      4, {     5,    21,    19,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(5, 21, 19, 2)
	{ kOpAnimPlay2,      4, {     7,     1,    27,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(7, 1, 27, 3)
	{ kOpAnimPlay2,      4, {     7,    20,     8,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(7, 20, 8, 3)
	{ kOpAnimPlay1,      4, {     0,     1,    33,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 1, 33, 2)
	{ kOpAnimPlay1,      4, {     1,     1,     3,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(1, 1, 3, 0)
	{ kOpAnimPlay1,      4, {     6,     1,    15,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(6, 1, 15, 2)
	{ kOpAnimPlay2,      4, {     2,     1,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(2, 1, 1, 0)
	{ kOpAnimPlay2,      4, {     5,     1,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(5, 1, 1, 0)
	{ kOpAnimPlay2,      4, {     3,     1,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(3, 1, 1, 0)
	{ kOpAnimPlay2,      4, {     5,     1,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(5, 1, 1, 0)
	{ kOpAnimPlay2,      4, {     2,     1,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(2, 1, 1, 0)
	{ kOpAnimPlay2,      4, {     5,     1,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(5, 1, 1, 0)
	{ kOpAnimPlay2,      4, {     2,     1,    12,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(2, 1, 12, 3)
	{ kOpAnimPlay2,      4, {     2,     1,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(2, 1, 1, 0)
	{ kOpUnsupported,    0, {     0,     0,     0,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_list(5, 0, 17, 4)
	{ kOpAnimPlay2,      4, {     5,     1,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(5, 1, 1, 0)
	{ kOpAnimPlay2,      4, {     2,     1,     1,     0,     0,     0 }, 0x00, 1, { { 0xa4ee, 2, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(2, 1, 1, 0)
	{ kOpAnimPlay1,      4, {     3,     1,    41,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(3, 1, 41, 2)
	{ kOpAnimPlay1,      4, {     4,     1,    25,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(4, 1, 25, 2)
	{ kOpUnsupported,    0, {     0,     0,     0,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_list(2, 0, 41, 4)
	{ kOpAnimPlay2,      4, {     2,     1,     1,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(2, 1, 1, 3)
	{ kOpUnsupported,    0, {     0,     0,     0,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_list(2, 0, 14, 3)
	{ kOpAnimPlay1,      4, {     2,     6,    40,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(2, 6, 40, 3)
	{ kOpUnsupported,    0, {     0,     0,     0,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_list(3, 0, 25, 4)
	{ kOpAnimPlay1,      4, {     0,     1,    21,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 1, 21, 2)
	{ kOpAnimPlay2,      4, {     2,     1,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(2, 1, 1, 0)
	{ kOpAnimPlay2,      4, {     2,     1,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(2, 1, 1, 0)
	{ kOpUnsupported,    0, {     0,     0,     0,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_list(2, 0, 13, 3)
	{ kOpAnimPlay2,      4, {     3,    17,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(3, 17, 1, 0)
	{ kOpAnimPlay2,      4, {     3,     7,    11,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(3, 7, 11, 3)
	{ kOpAnimPlay1,      4, {     2,     4,    58,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(2, 4, 58, 2)
	{ kOpAnimPlay2,      4, {     6,    10,     5,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(6, 10, 5, 3)
	{ kOpAnimPlay2,      4, {     7,     9,     9,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(7, 9, 9, 3)
	{ kOpAnimPlay2,      4, {     6,    10,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(6, 10, 1, 0)
	{ kOpAnimPlay2,      4, {     7,     9,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(7, 9, 1, 0)
	{ kOpUnsupported,    0, {     0,     0,     0,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_list(6, 0, 5, 7)
	{ kOpAnimPlay2,      4, {     6,     1,     5,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(6, 1, 5, 3)
	{ kOpAnimPlay2,      4, {     6,     5,     9,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(6, 5, 9, 3)
	{ kOpAnimPlay2,      4, {     7,     1,     9,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(7, 1, 9, 3)
	{ kOpUnsupported,    0, {     0,     0,     0,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_list(1, 0, 37, 3)
	{ kOpAnimPlay1,      4, {     0,     1,    17,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 1, 17, 2)
	{ kOpAnimPlay2,      4, {     0,     1,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(0, 1, 1, 0)
	{ kOpAnimPlay1,      4, {     0,     1,    53,     1,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 1, 53, 1)
	{ kOpAnimPlay2,      4, {     0,     1,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(0, 1, 1, 0)
	{ kOpAnimPlay2,      4, {     0,     1,    11,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(0, 1, 11, 3)
};

// One scene procedure: where it sat in segment 0c55, and its effects. Index 0 is
// the empty procedure the records point at wherever a slot is unused -- the
// original has one `push bp; leave; retf` shared by every such slot.
static const CutsceneProc kCutsceneProcs[] = {
	{ 0x0e92,    0,  0 },
	{ 0x0e97,    0,  1 },
	{ 0x0eae,    1,  1 },
	{ 0x0eca,    2,  1 },
	{ 0x0ee1,    3,  1 },
	{ 0x0ef8,    4,  3 },
	{ 0x0f2d,    7,  3 },
	{ 0x0f54,   10,  1 },
	{ 0x0f66,   11,  1 },
	{ 0x0f78,   12,  3 },
	{ 0x0fc3,   15,  4 },
	{ 0x1017,   19,  3 },
	{ 0x1052,   22,  2 },
	{ 0x1075,   24,  2 },
	{ 0x1098,   26,  2 },
	{ 0x10bb,   28,  1 },
	{ 0x10d2,   29,  1 },
	{ 0x10e9,   30,  1 },
	{ 0x1105,   31,  1 },
	{ 0x111c,   32,  1 },
	{ 0x1142,   33,  2 },
	{ 0x1176,   35,  0 },
	{ 0x118e,   35,  1 },
	{ 0x11bf,   36,  1 },
	{ 0x11d6,   37,  1 },
	{ 0x11f2,   38,  1 },
	{ 0x120c,   39,  1 },
	{ 0x1228,   40,  2 },
	{ 0x1250,   42,  1 },
	{ 0x1267,   43,  1 },
	{ 0x1283,   44,  1 },
	{ 0x129a,   45,  1 },
	{ 0x12be,   46,  1 },
	{ 0x12d8,   47,  1 },
	{ 0x12ef,   48,  1 },
	{ 0x1306,   49,  1 },
	{ 0x131d,   50,  1 },
	{ 0x1334,   51,  1 },
	{ 0x1355,   52,  3 },
	{ 0x139c,   55,  2 },
	{ 0x13ca,   57,  1 },
	{ 0x13dc,   58,  1 },
	{ 0x13ee,   59,  1 },
	{ 0x1400,   60,  1 },
};

// Every record's step stream, in record order. A speaker step carries the dialog
// id the original reads off the speaker's own list as the scene runs; because a
// speaker's steps consume that list in order, which id belongs to which step is
// settled here rather than at run time.
static const CutsceneStep kCutsceneSteps[] = {
	// record 1
	{ 0, 100 },
	{ 0,   5 },
	// record 2
	{ 0,  27 },
	{ 2,   1 },
	{ 1,  20 },
	{ 2,   2 },
	{ 1,  21 },
	{ 2,   3 },
	{ 1,  22 },
	{ 20,   0 },
	{ 0,  25 },
	{ 20,   0 },
	{ 0, 100 },
	{ 0,   5 },
	// record 3
	{ 0,  20 },
	{ 1,   7 },
	{ 1,   8 },
	{ 1,   9 },
	{ 1,  10 },
	{ 1,  11 },
	{ 1,  12 },
	{ 1,   2 },
	{ 1,   3 },
	{ 0,   7 },
	{ 0,   1 },
	// record 4
	{ 0,  10 },
	{ 1,   1 },
	{ 20,   0 },
	{ 0,  40 },
	{ 20,   0 },
	{ 0,  25 },
	{ 20,   0 },
	{ 0,  50 },
	{ 2,  10 },
	{ 0,  20 },
	{ 0,   1 },
	// record 5
	{ 0,  10 },
	{ 1,   1 },
	{ 2,  30 },
	{ 1,   2 },
	{ 2,  31 },
	{ 1,   3 },
	{ 2,  32 },
	{ 1,   4 },
	{ 2,  33 },
	{ 1,   5 },
	{ 2,  34 },
	{ 1,   6 },
	{ 2,  35 },
	{ 1,   7 },
	{ 2,  36 },
	{ 1,   8 },
	{ 2,  37 },
	{ 1,   9 },
	{ 0,  30 },
	{ 0,   1 },
	// record 6
	{ 0,  25 },
	{ 20,   0 },
	{ 0,  50 },
	{ 2,  20 },
	{ 20,   0 },
	{ 0,  35 },
	{ 1,   1 },
	{ 2,  21 },
	{ 1,   2 },
	{ 2,  22 },
	{ 1,   3 },
	{ 2,  23 },
	{ 0,  20 },
	{ 0,   1 },
	// record 7
	{ 0,  20 },
	{ 1,   1 },
	{ 2,   2 },
	{ 1,   3 },
	{ 2,   4 },
	{ 0,  20 },
	{ 0,   1 },
	// record 8
	{ 0,  20 },
	{ 1,   1 },
	{ 2,  30 },
	{ 1,   2 },
	{ 2,  31 },
	{ 20,   0 },
	{ 1,   3 },
	{ 2,  32 },
	{ 1,   4 },
	{ 2,  33 },
	{ 1,   5 },
	{ 2,  34 },
	{ 1,   6 },
	{ 2,  35 },
	{ 1,   7 },
	{ 2,  36 },
	{ 0,  20 },
	{ 0,   1 },
	// record 9
	{ 2,  20 },
	{ 1,   1 },
	{ 2,  21 },
	{ 1,   2 },
	{ 2,  22 },
	{ 1,   3 },
	{ 2,  23 },
	{ 1,   4 },
	{ 2,  24 },
	{ 1,   5 },
	{ 2,  25 },
	{ 1,   6 },
	{ 20,   0 },
	{ 0, 100 },
	{ 0,   1 },
	// record 10
	{ 0,  60 },
	{ 1,   1 },
	{ 2,  20 },
	{ 1,   2 },
	{ 2,  21 },
	{ 1,   3 },
	{ 2,  22 },
	{ 1,   4 },
	{ 2,  23 },
	{ 1,   5 },
	{ 2,  24 },
	{ 1,   6 },
	{ 2,  25 },
	{ 20,   0 },
	{ 0, 100 },
	{ 0,   1 },
	// record 11
	{ 0,  65 },
	{ 20,   0 },
	{ 0,  25 },
	{ 20,   0 },
	{ 0,  30 },
	{ 20,   0 },
	{ 0,  30 },
	{ 2,   1 },
	{ 1,  10 },
	{ 0,  15 },
	{ 0,   1 },
	// record 12
	{ 0, 180 },
	{ 0,   1 },
	// record 13
	{ 0,   5 },
	{ 20,   0 },
	{ 0,  80 },
	{ 0,   1 },
	// record 14
	{ 0,   8 },
	{ 20,   0 },
	{ 0,  35 },
	{ 0,   1 },
	// record 15
	{ 0,  75 },
	{ 0,   1 },
};

// The 218-byte records, in the loader's own numbering. Index 0 is unused: the
// loader's argument runs 1..15, and the dispatch passes it straight through.
static const CutsceneRecord kCutsceneRecords[] = {
	{ nullptr, nullptr, -1, { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr }, 0, { 0, 0, 0, 0, 0, 0, 0 }, { 0, 0, 0, 0 }, { 0, 0, 0, 0, 0, 0 }, 0, 0 },
	{ "MW92BGR.PCX", nullptr, 4,
	  { "MW92SHUT.DL1", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
	  7, { 0, 0, 0, 0, 0, 0, 0 },
	  { 0, 0, 0, 0 }, { 0, 0, 0, 0, 0, 0 }, 0, 2 },
	{ "MW9_BGR.PCX", "MW9.TAL", 4,
	  { "MW9_YODL.DL1", "MW9_ALIE.DL1", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
	  6, { 1, 2, 3, 4, 5, 0, 0 },
	  { 161, 73, 196, 112 }, { 40, 40, 63, 55, 63, 55 }, 2, 12 },
	{ "MW4_BGR.PCX", "MW4.TAL", 4,
	  { "MW4_GSM.DL1", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
	  8, { 9, 0, 0, 0, 0, 0, 0 },
	  { 83, 72, 0, 0 }, { 55, 63, 55, 0, 0, 0 }, 14, 11 },
	{ "BOSSROOM.PCX", "mw3.tal", 6,
	  { "BOSSBALL.DL1", "BOS_LIGH.DL1", "BOS_ALI2.DL1", nullptr, nullptr, "BOS_BOS1.DL1", "BOS_GAM1.DL1", "BOS_MONI.DL1", nullptr, nullptr },
	  12, { 15, 17, 16, 18, 10, 0, 0 },
	  { 96, 78, 248, 69 }, { 58, 58, 63, 40, 63, 40 }, 25, 11 },
	{ "BOSSROOM.PCX", "mw2.tal", 6,
	  { "BOSSBALL.DL1", "BOS_LIGH.DL1", "BOS_ALI2.DL1", nullptr, nullptr, "BOS_BOS1.DL1", "BOS_GAM1.DL1", "BOS_MONI.DL1", nullptr, nullptr },
	  12, { 15, 17, 16, 18, 0, 0, 0 },
	  { 96, 78, 248, 69 }, { 58, 58, 63, 40, 63, 40 }, 36, 20 },
	{ "BOSSROOM.PCX", "mw8.tal", 6,
	  { "BOSSBALL.DL1", "BOS_LIGH.DL1", "BOS_ALI2.DL1", "BOS_FIST.DL1", "BOS_ALWA.DL1", "BOS_BOS1.DL1", "BOS_GAM1.DL1", "BOS_MONI.DL1", nullptr, nullptr },
	  13, { 15, 17, 16, 18, 20, 0, 19 },
	  { 96, 78, 248, 69 }, { 58, 58, 63, 40, 63, 40 }, 56, 14 },
	{ "BOSSROOM.PCX", "mw10.tal", 6,
	  { "BOSSBALL.DL1", "BOS_LIGH.DL1", "BOS_ALI2.DL1", nullptr, nullptr, "BOS_BOS1.DL1", "BOS_GAM1.DL1", nullptr, nullptr, nullptr },
	  12, { 15, 17, 16, 18, 0, 0, 0 },
	  { 96, 78, 248, 69 }, { 58, 58, 63, 40, 63, 40 }, 70, 7 },
	{ "BOSSROOM.PCX", "mw1.tal", 6,
	  { "BOSSBALL.DL1", "BOS_LIGH.DL1", "BOS_ALI2.DL1", nullptr, nullptr, "BOS_BOS1.DL1", "BOS_GAM1.DL1", nullptr, nullptr, nullptr },
	  12, { 15, 17, 16, 18, 21, 0, 22 },
	  { 96, 78, 248, 69 }, { 58, 58, 63, 40, 63, 40 }, 77, 18 },
	{ "BOSSROOM.PCX", "mw11.tal", 6,
	  { "BOSSBALL.DL1", "BOS_LIGH.DL1", "BOS_MAIN.DL1", nullptr, nullptr, "BOS_BOS1.DL1", "BOS_GAM1.DL1", nullptr, nullptr, nullptr },
	  14, { 24, 17, 23, 18, 25, 0, 0 },
	  { 108, 40, 248, 69 }, { 40, 40, 63, 40, 63, 40 }, 95, 15 },
	{ "TORTURE.PCX", "mw7.tal", 4,
	  { "TOR_STUF.DL1", nullptr, "TOR_ALIE.DL1", "TOR_UNCL.DL1", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
	  27, { 29, 31, 28, 26, 32, 0, 0 },
	  { 187, 91, 255, 93 }, { 51, 51, 63, 63, 63, 63 }, 110, 16 },
	{ "GAME18.PCX", "mw5.tal", 4,
	  { nullptr, "CABINET.DL1", "HAMMER.DL1", nullptr, nullptr, "BEN_WALK.DL1", "MW5_ALI1.DL1", "MW5_ALI2.DL1", nullptr, nullptr },
	  37, { 33, 34, 35, 36, 38, 0, 0 },
	  { 79, 102, 261, 71 }, { 63, 63, 63, 63, 63, 63 }, 126, 11 },
	{ "MW12.PCX", nullptr, 4,
	  { "WAI_FAN.DL1", "MW12_GUA.DL1", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
	  39, { 0, 0, 0, 0, 0, 0, 0 },
	  { 79, 102, 261, 71 }, { 63, 63, 63, 63, 63, 63 }, 137, 2 },
	{ "MW5_II.PCX", nullptr, 7,
	  { "MW5_SHUT.DL1", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
	  40, { 0, 0, 0, 0, 41, 0, 0 },
	  { 79, 102, 261, 71 }, { 63, 63, 63, 63, 63, 63 }, 139, 4 },
	{ "MW_CLIFF.PCX", nullptr, -1,
	  { "MW_CLIFF.DL1", nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
	  42, { 0, 0, 0, 0, 43, 0, 0 },
	  { 79, 102, 261, 71 }, { 63, 63, 63, 63, 63, 63 }, 143, 4 },
	{ "ALIESHP1.PCX", nullptr, 0,
	  { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
	  0, { 0, 0, 0, 0, 0, 0, 0 },
	  { 79, 102, 261, 71 }, { 63, 63, 63, 63, 63, 63 }, 147, 2 },
};

// The flag stores the dispatch arms run besides their latch.
static const ScriptEffect kCutsceneArmEffects[] = {
	{ kOpSetFlag,        2, { 42827,     0,     0,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// set_flag(0xa74b, 0)
	{ kOpSetFlag,        2, { 13256,     1,     0,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// set_flag(0x33c8, 1)
	{ kOpSetFlag,        2, { 42710,     0,     0,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// set_flag(0xa6d6, 0)
	{ kOpSetFlag,        2, { 42711,     1,     0,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// set_flag(0xa6d7, 1)
};

// One arm of CUTSCENE:sub_0de60, keyed by the scene id a room raises.
static const CutsceneArm kCutsceneArms[] = {
	{  1, 0x3395, 0, { { 0x0000, 0, false }, { 0x0000, 0, false } }, 2, { 1, 2 },   0, 2, false },
	{  2, 0x3396, 0, { { 0x0000, 0, false }, { 0x0000, 0, false } }, 1, { 13, 0 },   2, 0, false },
	{  3, 0x33d4, 1, { { 0xa7b4, 0, false }, { 0x0000, 0, false } }, 1, { 12, 0 },   2, 0, false },
	{  4, 0x0000, 0, { { 0x0000, 0, false }, { 0x0000, 0, false } }, 1, { 14, 0 },   2, 0, false },
	{  5, 0x3399, 0, { { 0x0000, 0, false }, { 0x0000, 0, false } }, 1, { 3, 0 },   2, 0, false },
	{  6, 0x339a, 0, { { 0x0000, 0, false }, { 0x0000, 0, false } }, 1, { 11, 0 },   2, 2, false },
	{  7, 0x339b, 0, { { 0x0000, 0, false }, { 0x0000, 0, false } }, 1, { 8, 0 },   4, 0, false },
	{  8, 0x339c, 0, { { 0x0000, 0, false }, { 0x0000, 0, false } }, 1, { 5, 0 },   4, 0, false },
	{  9, 0x339d, 0, { { 0x0000, 0, false }, { 0x0000, 0, false } }, 1, { 4, 0 },   4, 0, false },
	{ 10, 0x339e, 0, { { 0x0000, 0, false }, { 0x0000, 0, false } }, 1, { 10, 0 },   4, 0, false },
	{ 11, 0x339f, 0, { { 0x0000, 0, false }, { 0x0000, 0, false } }, 1, { 7, 0 },   4, 0, false },
	{ 12, 0x33a0, 0, { { 0x0000, 0, false }, { 0x0000, 0, false } }, 1, { 6, 0 },   4, 0, false },
	{ 13, 0x33a1, 1, { { 0xa7e4, 1, false }, { 0x0000, 0, false } }, 1, { 9, 0 },   4, 0, false },
	{ 14, 0x33a2, 0, { { 0x0000, 0, false }, { 0x0000, 0, false } }, 0, { 0, 0 },   4, 0, true },
};

const CutsceneArm *cutsceneArm(byte id) {
	for (uint i = 0; i < ARRAYSIZE(kCutsceneArms); i++)
		if (kCutsceneArms[i].id == id)
			return &kCutsceneArms[i];
	return nullptr;
}

uint cutsceneArmCount() {
	return ARRAYSIZE(kCutsceneArms);
}

const CutsceneArm *cutsceneArmAt(uint index) {
	return index < ARRAYSIZE(kCutsceneArms) ? &kCutsceneArms[index] : nullptr;
}

const CutsceneRecord *cutsceneRecord(uint number) {
	if (number == 0 || number >= ARRAYSIZE(kCutsceneRecords))
		return nullptr;
	return &kCutsceneRecords[number];
}

uint cutsceneRecordCount() {
	return ARRAYSIZE(kCutsceneRecords) - 1;
}

const CutsceneStep *cutsceneSteps(const CutsceneRecord &record, uint &count) {
	count = record.stepCount;
	return count ? &kCutsceneSteps[record.firstStep] : nullptr;
}

const ScriptEffect *cutsceneProcEffects(uint proc, uint &count) {
	count = 0;
	if (proc >= ARRAYSIZE(kCutsceneProcs))
		return nullptr;
	count = kCutsceneProcs[proc].count;
	return count ? &kCutsceneEffects[kCutsceneProcs[proc].first] : nullptr;
}

uint cutsceneProcAddr(uint proc) {
	return proc < ARRAYSIZE(kCutsceneProcs) ? kCutsceneProcs[proc].addr : 0;
}

uint cutsceneProcCount() {
	return ARRAYSIZE(kCutsceneProcs);
}

const ScriptEffect *cutsceneArmEffects(const CutsceneArm &arm, uint &count) {
	count = arm.count;
	return count ? &kCutsceneArmEffects[arm.first] : nullptr;
}

} // End of namespace Alien
