/* ScummVM - Graphic Adventure Engine
 *
 * ScummVM is the legal property of its developers, whose names
 * are too numerous to list here. Please refer to the COPYRIGHT
 * file distributed with this source distribution.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

// Generated by tools/gen_hotspots.py of the Alien Incident reverse
// engineering repository -- do not edit by hand.
//
// The original has no hotspot resource: each room overlay registers its
// rectangles by calling segment 1336 with immediate arguments, so the table
// below is those arguments, lifted out of the overlay code.
//
//   342 of 429 registration sites are decoded, in 39 rooms.
//   The remaining 87 take their arguments from registers, which means
//   the rectangle itself is state dependent -- those objects stay unclickable
//   until their room's script is ported.

#include "alien/hotspots.h"

namespace Alien {

static const Hotspot kHotspots[] = {
	{  110,  53,  137,  84,  1,  1, 10, 1, { 0, 0, 0, 0 } },	// ovr_03_0e57_room_3_-_uncle's_lab.asm:492
	{  134,  65,  155,  81,  2,  2,  5, 1, { 31, 0, 0, 0 } },	// ovr_03_0e57_room_3_-_uncle's_lab.asm:500
	{  135,  54,  151,  67,  3, 20,  1, 1, { 0, 0, 0, 0 } },	// ovr_03_0e57_room_3_-_uncle's_lab.asm:511
	{  200,  63,  218,  81,  4,  4,  1, 1, { 0, 0, 0, 0 } },	// ovr_03_0e57_room_3_-_uncle's_lab.asm:522
	{  174,  43,  190,  62,  5,  5,  5, 1, { 21, 0, 0, 0 } },	// ovr_03_0e57_room_3_-_uncle's_lab.asm:530
	{  295,  14,  385, 112,  7,  7,  5, 2, { 1, 2, 0, 0 } },	// ovr_03_0e57_room_3_-_uncle's_lab.asm:561
	{   38,   0,   86,  70,  8,  8,  5, 1, { 0, 0, 0, 0 } },	// ovr_03_0e57_room_3_-_uncle's_lab.asm:569
	{    0,  70,   80, 160,  9,  9,  5, 1, { 0, 0, 0, 0 } },	// ovr_03_0e57_room_3_-_uncle's_lab.asm:577
	{   76, 118,  112, 160,  9,  9,  5, 1, { 0, 0, 0, 0 } },	// ovr_03_0e57_room_3_-_uncle's_lab.asm:585
	{  100, 133,  114, 160,  9,  9,  5, 1, { 0, 0, 0, 0 } },	// ovr_03_0e57_room_3_-_uncle's_lab.asm:593
	{  115, 142,  131, 160,  9,  9,  5, 1, { 0, 0, 0, 0 } },	// ovr_03_0e57_room_3_-_uncle's_lab.asm:601
	{  184, 106,  198, 124, 10, 10, 10, 3, { 6, 7, 9, 0 } },	// ovr_03_0e57_room_3_-_uncle's_lab.asm:612
	{  197,  95,  221, 126, 10, 10, 10, 3, { 6, 7, 9, 0 } },	// ovr_03_0e57_room_3_-_uncle's_lab.asm:623
	{  126, 130,  143, 142, 13, 12,  1, 1, { 0, 0, 0, 0 } },	// ovr_03_0e57_room_3_-_uncle's_lab.asm:655
	{  205,  51,  211,  56, 15, 17,  1, 1, { 0, 0, 0, 0 } },	// ovr_03_0e57_room_3_-_uncle's_lab.asm:687
	{  188,  36,  224,  95,  1, 10,  3, 1, { 12, 0, 0, 0 } },	// ovr_06_0e5f_room_6_-_upstairs_landing.asm:444
	{  230,  64,  257, 100,  2,  7,  5, 1, { 3, 0, 0, 0 } },	// ovr_06_0e5f_room_6_-_upstairs_landing.asm:467
	{  230,  64,  257, 100,  2, 12,  5, 1, { 16, 0, 0, 0 } },	// ovr_06_0e5f_room_6_-_upstairs_landing.asm:500
	{   88, 127,  225, 159,  5, 20,  5, 1, { 0, 0, 0, 0 } },	// ovr_06_0e5f_room_6_-_upstairs_landing.asm:525
	{  122, 118,  319, 159,  5, 20,  5, 1, { 0, 0, 0, 0 } },	// ovr_06_0e5f_room_6_-_upstairs_landing.asm:533
	{  129, 109,  224, 117,  5, 20,  5, 1, { 0, 0, 0, 0 } },	// ovr_06_0e5f_room_6_-_upstairs_landing.asm:541
	{  150,  43,  175,  60,  6, 30,  5, 1, { 25, 0, 0, 0 } },	// ovr_06_0e5f_room_6_-_upstairs_landing.asm:549
	{  129,  21,  160,  91,  1, 14,  5, 1, { 0, 0, 0, 0 } },	// ovr_07_0e63_room_7_-_bedroom.asm:636
	{   54,  50,   95, 114,  2, 13,  5, 1, { 0, 0, 0, 0 } },	// ovr_07_0e63_room_7_-_bedroom.asm:647
	{   88,  74,  114, 134,  2, 13,  5, 1, { 0, 0, 0, 0 } },	// ovr_07_0e63_room_7_-_bedroom.asm:655
	{  114,  80,  132, 134,  2, 13,  5, 1, { 0, 0, 0, 0 } },	// ovr_07_0e63_room_7_-_bedroom.asm:663
	{  132,  85,  155, 117,  2, 13,  5, 1, { 0, 0, 0, 0 } },	// ovr_07_0e63_room_7_-_bedroom.asm:671
	{  185,  22,  209,  62,  3,  1,  5, 1, { 19, 0, 0, 0 } },	// ovr_07_0e63_room_7_-_bedroom.asm:679
	{  179,  68,  218,  98,  4,  2,  5, 1, { 21, 0, 0, 0 } },	// ovr_07_0e63_room_7_-_bedroom.asm:687
	{  195,  83,  210,  96,  5, 30,  1, 2, { 14, 15, 0, 0 } },	// ovr_07_0e63_room_7_-_bedroom.asm:697
	{   28,  84,   69, 120,  6, 12,  5, 1, { 0, 0, 0, 0 } },	// ovr_07_0e63_room_7_-_bedroom.asm:705
	{  185,  66,  195,  71,  7, 20,  1, 1, { 0, 0, 0, 0 } },	// ovr_07_0e63_room_7_-_bedroom.asm:716
	{   43, 103,   69, 119,  8, 23,  3, 1, { 0, 0, 0, 0 } },	// ovr_07_0e63_room_7_-_bedroom.asm:727
	{   43, 103,   69, 119,  8, 24,  4, 1, { 0, 0, 0, 0 } },	// ovr_07_0e63_room_7_-_bedroom.asm:738
	{   49, 106,   59, 113,  9, 25,  1, 1, { 0, 0, 0, 0 } },	// ovr_07_0e63_room_7_-_bedroom.asm:751
	{   14,  34,   80,  46, 10,  5,  5, 1, { 0, 0, 0, 0 } },	// ovr_07_0e63_room_7_-_bedroom.asm:759
	{   62,  73,   83,  87, 11, 10,  9, 1, { 0, 0, 0, 0 } },	// ovr_07_0e63_room_7_-_bedroom.asm:770
	{   77,  69,   99,  83, 11, 10,  9, 1, { 0, 0, 0, 0 } },	// ovr_07_0e63_room_7_-_bedroom.asm:779
	{   67,  62,   98,  81, 11, 16,  9, 1, { 0, 0, 0, 0 } },	// ovr_07_0e63_room_7_-_bedroom.asm:790
	{   68,  77,   80,  83, 12, 18,  1, 1, { 0, 0, 0, 0 } },	// ovr_07_0e63_room_7_-_bedroom.asm:801
	{    0,  89,   19, 106, 11, 15,  5, 1, { 17, 0, 0, 0 } },	// ovr_07_0e63_room_7_-_bedroom.asm:809
	{  208,  34,  233, 103, 13, 11,  4, 1, { 0, 0, 0, 0 } },	// ovr_07_0e63_room_7_-_bedroom.asm:868
	{  220,  48,  264, 105,  1,  1,  5, 1, { 20, 0, 0, 0 } },	// ovr_08_0e67_room_8_-_library.asm:508
	{  220,  48,  264, 105,  2, 21,  5, 2, { 10, 42, 0, 0 } },	// ovr_08_0e67_room_8_-_library.asm:520
	{   82,  46,  134, 118,  3, 30,  5, 2, { 22, 44, 0, 0 } },	// ovr_08_0e67_room_8_-_library.asm:530
	{  135,  40,  166, 104,  4, 31,  5, 1, { 0, 0, 0, 0 } },	// ovr_08_0e67_room_8_-_library.asm:538
	{  167,  41,  175, 113,  3,  2,  5, 2, { 22, 44, 0, 0 } },	// ovr_08_0e67_room_8_-_library.asm:548
	{  176,  41,  184, 117,  3,  2,  5, 2, { 22, 44, 0, 0 } },	// ovr_08_0e67_room_8_-_library.asm:558
	{  185,  41,  192, 120,  3,  2,  5, 2, { 22, 44, 0, 0 } },	// ovr_08_0e67_room_8_-_library.asm:568
	{  193,  41,  201, 125,  3,  2,  5, 2, { 22, 44, 0, 0 } },	// ovr_08_0e67_room_8_-_library.asm:578
	{  202,  42,  209, 128,  3,  2,  5, 2, { 22, 44, 0, 0 } },	// ovr_08_0e67_room_8_-_library.asm:588
	{  210,  48,  219, 125,  3,  2,  5, 2, { 22, 44, 0, 0 } },	// ovr_08_0e67_room_8_-_library.asm:598
	{  117,  88,  126,  96,  5,  3,  5, 1, { 21, 0, 0, 0 } },	// ovr_08_0e67_room_8_-_library.asm:606
	{   97,  13,  115,  43,  6,  4,  5, 1, { 63, 0, 0, 0 } },	// ovr_08_0e67_room_8_-_library.asm:630
	{   97,  13,  115,  43,  6,  4,  5, 1, { 76, 0, 0, 0 } },	// ovr_08_0e67_room_8_-_library.asm:639
	{  294,  81,  300, 110,  8, 10,  4, 1, { 0, 0, 0, 0 } },	// ovr_08_0e67_room_8_-_library.asm:705
	{  276,  95,  294, 104,  9, 12,  1, 1, { 0, 0, 0, 0 } },	// ovr_08_0e67_room_8_-_library.asm:716
	{  283,  85,  294,  92, 10, 13,  1, 1, { 0, 0, 0, 0 } },	// ovr_08_0e67_room_8_-_library.asm:727
	{  301,  51,  364, 141,  3,  5,  5, 2, { 22, 44, 0, 0 } },	// ovr_08_0e67_room_8_-_library.asm:737
	{  234, 122,  246, 132, 11, 20,  1, 1, { 0, 0, 0, 0 } },	// ovr_08_0e67_room_8_-_library.asm:748
	{  338,  95,  354, 113, 12, 40,  5, 1, { 26, 0, 0, 0 } },	// ovr_08_0e67_room_8_-_library.asm:760
	{  138,  31,  181,  93,  1,  7,  5, 1, { 0, 0, 0, 0 } },	// ovr_0a_0e73_room_10_-_kitchen.asm:347
	{  127, 117,  163, 160,  3, 10,  5, 1, { 0, 0, 0, 0 } },	// ovr_0a_0e73_room_10_-_kitchen.asm:371
	{  113, 118,  126, 160,  3, 10,  5, 1, { 0, 0, 0, 0 } },	// ovr_0a_0e73_room_10_-_kitchen.asm:379
	{  101, 120,  112, 160,  3, 10,  5, 1, { 0, 0, 0, 0 } },	// ovr_0a_0e73_room_10_-_kitchen.asm:387
	{   81, 123,  100, 160,  3, 10,  5, 1, { 0, 0, 0, 0 } },	// ovr_0a_0e73_room_10_-_kitchen.asm:395
	{  185,  39,  256,  98,  4, 12,  5, 1, { 0, 0, 0, 0 } },	// ovr_0a_0e73_room_10_-_kitchen.asm:403
	{  176,  79,  256, 115,  4, 12,  5, 1, { 0, 0, 0, 0 } },	// ovr_0a_0e73_room_10_-_kitchen.asm:411
	{  200, 116,  255, 125,  4, 12,  5, 1, { 0, 0, 0, 0 } },	// ovr_0a_0e73_room_10_-_kitchen.asm:419
	{   16,  83,   47, 124,  5, 13,  5, 1, { 6, 0, 0, 0 } },	// ovr_0a_0e73_room_10_-_kitchen.asm:427
	{   48,  86,   55, 123,  5, 13,  5, 1, { 6, 0, 0, 0 } },	// ovr_0a_0e73_room_10_-_kitchen.asm:435
	{  112,  66,  123,  80,  6, 18,  5, 1, { 1, 0, 0, 0 } },	// ovr_0a_0e73_room_10_-_kitchen.asm:445
	{  107,  63,  124,  72,  7, 20,  1, 1, { 0, 0, 0, 0 } },	// ovr_0a_0e73_room_10_-_kitchen.asm:458
	{  109,  73,  124,  82,  8, 21,  1, 1, { 0, 0, 0, 0 } },	// ovr_0a_0e73_room_10_-_kitchen.asm:469
	{  111,  84,  122,  94,  9, 27,  1, 1, { 2, 0, 0, 0 } },	// ovr_0a_0e73_room_10_-_kitchen.asm:478
	{  179,  79,  189,  85, 10, 25,  1, 1, { 0, 0, 0, 0 } },	// ovr_0a_0e73_room_10_-_kitchen.asm:489
	{  200,  80,  206,  88, 11, 40,  1, 1, { 0, 0, 0, 0 } },	// ovr_0a_0e73_room_10_-_kitchen.asm:500
	{   51,  81,   70,  90, 12, 29,  1, 1, { 0, 0, 0, 0 } },	// ovr_0a_0e73_room_10_-_kitchen.asm:511
	{  102,  76,  116,  93,  2,  2,  5, 1, { 5, 0, 0, 0 } },	// ovr_0b_0e77_room_11_-_living_room.asm:313
	{  102,  76,  116,  93,  3, 11,  1, 1, { 0, 0, 0, 0 } },	// ovr_0b_0e77_room_11_-_living_room.asm:324
	{  190, 117,  209, 133,  5, 10,  1, 1, { 8, 0, 0, 0 } },	// ovr_0b_0e77_room_11_-_living_room.asm:348
	{   95,  91,  112, 102,  7,  6,  1, 1, { 0, 0, 0, 0 } },	// ovr_0b_0e77_room_11_-_living_room.asm:383
	{  251,  13,  319, 115,  8,  7,  5, 1, { 0, 0, 0, 0 } },	// ovr_0b_0e77_room_11_-_living_room.asm:391
	{  176,  76,  196,  90,  9,  9,  1, 1, { 0, 0, 0, 0 } },	// ovr_0b_0e77_room_11_-_living_room.asm:402
	{  107,  97,  122, 107,  3,  2,  5, 1, { 2, 0, 0, 0 } },	// ovr_0d_0e6f_room_13_-_basement.asm:405
	{  213,  47,  219, 121,  4,  5,  5, 1, { 3, 0, 0, 0 } },	// ovr_0d_0e6f_room_13_-_basement.asm:413
	{  220,  30,  237, 128,  4,  5,  5, 1, { 3, 0, 0, 0 } },	// ovr_0d_0e6f_room_13_-_basement.asm:421
	{  238,  30,  251, 135,  4,  5,  5, 1, { 3, 0, 0, 0 } },	// ovr_0d_0e6f_room_13_-_basement.asm:429
	{  252,  30,  260, 139,  4,  5,  5, 1, { 3, 0, 0, 0 } },	// ovr_0d_0e6f_room_13_-_basement.asm:437
	{  261,  30,  268, 134,  4,  5,  5, 1, { 3, 0, 0, 0 } },	// ovr_0d_0e6f_room_13_-_basement.asm:445
	{  269,  30,  284, 130,  4,  5,  5, 1, { 3, 0, 0, 0 } },	// ovr_0d_0e6f_room_13_-_basement.asm:453
	{   91,  88,  103,  99,  5,  3,  1, 1, { 0, 0, 0, 0 } },	// ovr_0d_0e6f_room_13_-_basement.asm:464
	{  104,  91,  113, 104,  5,  3,  1, 1, { 0, 0, 0, 0 } },	// ovr_0d_0e6f_room_13_-_basement.asm:473
	{  191,  80,  205, 102,  7, 12,  1, 1, { 0, 0, 0, 0 } },	// ovr_0d_0e6f_room_13_-_basement.asm:497
	{  191,  80,  205, 102,  8, 11,  5, 1, { 17, 0, 0, 0 } },	// ovr_0d_0e6f_room_13_-_basement.asm:506
	{  184,  13,  268,  93,  1,  1,  5, 1, { 1, 0, 0, 0 } },	// ovr_0e_0e83_room_14_-_closet_shaft___chimney.asm:247
	{  141,  94,  203, 122,  2,  2,  5, 1, { 0, 0, 0, 0 } },	// ovr_0e_0e83_room_14_-_closet_shaft___chimney.asm:255
	{   93, 118,  140, 143,  2,  2,  5, 1, { 0, 0, 0, 0 } },	// ovr_0e_0e83_room_14_-_closet_shaft___chimney.asm:263
	{    0,   0,   57,  96,  2,  3,  5, 1, { 0, 0, 0, 0 } },	// ovr_0e_0e83_room_14_-_closet_shaft___chimney.asm:271
	{    0,  90,   38, 147,  2,  3,  5, 1, { 0, 0, 0, 0 } },	// ovr_0e_0e83_room_14_-_closet_shaft___chimney.asm:279
	{  294,  85,  319, 159,  3,  4,  5, 1, { 0, 0, 0, 0 } },	// ovr_0e_0e83_room_14_-_closet_shaft___chimney.asm:287
	{  258,  47,  269,  60,  5,  7,  5, 1, { 3, 0, 0, 0 } },	// ovr_0e_0e83_room_14_-_closet_shaft___chimney.asm:358
	{  248,  24,  274,  98,  2,  2,  5, 1, { 0, 0, 0, 0 } },	// ovr_0f_0e5b_room_15_-_entrance_hall_sali.asm:303
	{  526,  26,  555, 106,  3,  4,  5, 1, { 0, 0, 0, 0 } },	// ovr_0f_0e5b_room_15_-_entrance_hall_sali.asm:311
	{  364,   0,  513, 107,  4,  6,  5, 1, { 0, 0, 0, 0 } },	// ovr_0f_0e5b_room_15_-_entrance_hall_sali.asm:319
	{  206,  71,  319, 159,  2,  2,  5, 1, { 0, 0, 0, 0 } },	// ovr_11_0eab_room_17_-_observatory_entrance.asm:233
	{  155,  43,  189,  94,  1,  3,  5, 1, { 5, 0, 0, 0 } },	// ovr_12_0e6b_room_18_-_sitting_room.asm:362
	{  227,  50,  244, 105,  3,  4,  5, 1, { 6, 0, 0, 0 } },	// ovr_12_0e6b_room_18_-_sitting_room.asm:392
	{  190,  50,  226,  65,  3,  4,  5, 1, { 6, 0, 0, 0 } },	// ovr_12_0e6b_room_18_-_sitting_room.asm:400
	{   70,  59,  103,  89,  4,  5,  5, 1, { 10, 0, 0, 0 } },	// ovr_12_0e6b_room_18_-_sitting_room.asm:408
	{  141,  76,  177,  94,  5,  6,  5, 1, { 25, 0, 0, 0 } },	// ovr_12_0e6b_room_18_-_sitting_room.asm:416
	{  129,  95,  188, 132,  5,  6,  5, 1, { 25, 0, 0, 0 } },	// ovr_12_0e6b_room_18_-_sitting_room.asm:424
	{  140,  92,  155, 103,  6, 20,  1, 1, { 0, 0, 0, 0 } },	// ovr_12_0e6b_room_18_-_sitting_room.asm:435
	{  245,  39,  280, 114,  8, 10,  5, 1, { 0, 0, 0, 0 } },	// ovr_12_0e6b_room_18_-_sitting_room.asm:457
	{   28, 112,   69, 160,  9, 12,  5, 1, { 2, 0, 0, 0 } },	// ovr_12_0e6b_room_18_-_sitting_room.asm:465
	{  105,  88,  115, 109, 10, 13,  4, 1, { 0, 0, 0, 0 } },	// ovr_12_0e6b_room_18_-_sitting_room.asm:490
	{   87,  98,   94, 104, 11,  8,  1, 1, { 0, 0, 0, 0 } },	// ovr_12_0e6b_room_18_-_sitting_room.asm:501
	{  120,  23,  206,  43, 12, 15,  5, 1, { 17, 0, 0, 0 } },	// ovr_12_0e6b_room_18_-_sitting_room.asm:509
	{   85,  65,  103,  83, 13, 16,  1, 1, { 0, 0, 0, 0 } },	// ovr_12_0e6b_room_18_-_sitting_room.asm:520
	{   40,  90,   66, 110, 14, 17,  5, 1, { 26, 0, 0, 0 } },	// ovr_12_0e6b_room_18_-_sitting_room.asm:528
	{  217,  31,  233,  53, 15, 40,  5, 1, { 38, 0, 0, 0 } },	// ovr_12_0e6b_room_18_-_sitting_room.asm:536
	{  116,  52,  131,  62, 16, 41,  5, 1, { 39, 0, 0, 0 } },	// ovr_12_0e6b_room_18_-_sitting_room.asm:544
	{   78,  35,   95,  54, 17, 42,  5, 1, { 40, 0, 0, 0 } },	// ovr_12_0e6b_room_18_-_sitting_room.asm:552
	{   32,  41,   72,  73, 18, 43,  5, 1, { 41, 0, 0, 0 } },	// ovr_12_0e6b_room_18_-_sitting_room.asm:560
	{   57,  98,   76, 120,  1,  1, 10, 1, { 0, 0, 0, 0 } },	// ovr_13_0eb3_room_19_-_observatory_interior.asm:407
	{   54,   0,  151,  55,  2,  2,  5, 1, { 0, 0, 0, 0 } },	// ovr_13_0eb3_room_19_-_observatory_interior.asm:415
	{   89,  56,  151, 132,  2,  2,  5, 1, { 0, 0, 0, 0 } },	// ovr_13_0eb3_room_19_-_observatory_interior.asm:423
	{  152,  70,  162, 123,  2,  2,  5, 1, { 0, 0, 0, 0 } },	// ovr_13_0eb3_room_19_-_observatory_interior.asm:431
	{  163,  80,  173, 117,  2,  2,  5, 1, { 0, 0, 0, 0 } },	// ovr_13_0eb3_room_19_-_observatory_interior.asm:439
	{  174,  80,  191, 111,  2,  2,  5, 1, { 0, 0, 0, 0 } },	// ovr_13_0eb3_room_19_-_observatory_interior.asm:447
	{  227,   0,  248,  96,  4,  4,  5, 1, { 0, 0, 0, 0 } },	// ovr_13_0eb3_room_19_-_observatory_interior.asm:475
	{  248,   0,  270,  41,  4,  4,  5, 1, { 0, 0, 0, 0 } },	// ovr_13_0eb3_room_19_-_observatory_interior.asm:483
	{   90,  73,  136, 139,  5,  8,  5, 3, { 22, 23, 24, 0 } },	// ovr_13_0eb3_room_19_-_observatory_interior.asm:494
	{  209,  41,  218,  48,  7, 10,  5, 1, { 7, 0, 0, 0 } },	// ovr_13_0eb3_room_19_-_observatory_interior.asm:517
	{  209,  41,  218,  48,  8, 11,  1, 1, { 0, 0, 0, 0 } },	// ovr_13_0eb3_room_19_-_observatory_interior.asm:528
	{  201,  62,  216,  65,  9, 12,  5, 1, { 19, 0, 0, 0 } },	// ovr_13_0eb3_room_19_-_observatory_interior.asm:536
	{   70,  13,  151,  61,  1,  5,  5, 1, { 0, 0, 0, 0 } },	// ovr_15_0ea7_room_21_-_yodle's_tree_hut.asm:716
	{   80,  62,  175,  82,  1,  5,  5, 1, { 0, 0, 0, 0 } },	// ovr_15_0ea7_room_21_-_yodle's_tree_hut.asm:724
	{   97,  83,  195, 134,  1,  5,  5, 1, { 0, 0, 0, 0 } },	// ovr_15_0ea7_room_21_-_yodle's_tree_hut.asm:732
	{  143, 110,  195, 140,  2,  4,  5, 1, { 0, 0, 0, 0 } },	// ovr_15_0ea7_room_21_-_yodle's_tree_hut.asm:740
	{  139,  81,  185, 128,  3,  1,  6, 1, { 0, 0, 0, 0 } },	// ovr_15_0ea7_room_21_-_yodle's_tree_hut.asm:753
	{  139,  81,  185, 128,  4, 12,  6, 1, { 0, 0, 0, 0 } },	// ovr_15_0ea7_room_21_-_yodle's_tree_hut.asm:763
	{  210,  80,  326, 102,  6,  3,  5, 1, { 0, 0, 0, 0 } },	// ovr_15_0ea7_room_21_-_yodle's_tree_hut.asm:780
	{  218, 102,  336, 128,  6,  3,  5, 1, { 0, 0, 0, 0 } },	// ovr_15_0ea7_room_21_-_yodle's_tree_hut.asm:788
	{  417,   0,  545,  88,  9, 10,  5, 1, { 0, 0, 0, 0 } },	// ovr_15_0ea7_room_21_-_yodle's_tree_hut.asm:830
	{  445,  89,  545, 117,  9, 10,  5, 1, { 0, 0, 0, 0 } },	// ovr_15_0ea7_room_21_-_yodle's_tree_hut.asm:838
	{  589,   0,  620, 160, 10, 20,  5, 1, { 0, 0, 0, 0 } },	// ovr_15_0ea7_room_21_-_yodle's_tree_hut.asm:846
	{  603,   0,  638, 160,  1,  3,  5, 1, { 0, 0, 0, 0 } },	// ovr_16_0ea3_room_22_-_parlor___teleport.asm:314
	{  100,  33,  151, 111,  2,  1,  5, 1, { 3, 0, 0, 0 } },	// ovr_16_0ea3_room_22_-_parlor___teleport.asm:322
	{  115,  53,  137,  78,  3,  5, 10, 1, { 0, 0, 0, 0 } },	// ovr_16_0ea3_room_22_-_parlor___teleport.asm:333
	{  152,  54,  163,  87,  4,  6,  5, 1, { 10, 0, 0, 0 } },	// ovr_16_0ea3_room_22_-_parlor___teleport.asm:341
	{  152,  88,  166, 106,  5,  7,  5, 1, { 11, 0, 0, 0 } },	// ovr_16_0ea3_room_22_-_parlor___teleport.asm:349
	{  119,  79,  132, 108,  6,  9,  1, 1, { 0, 0, 0, 0 } },	// ovr_16_0ea3_room_22_-_parlor___teleport.asm:360
	{  427,  62,  444,  84,  7,  4,  5, 1, { 4, 0, 0, 0 } },	// ovr_16_0ea3_room_22_-_parlor___teleport.asm:368
	{    0,   0,   15, 160,  8,  8,  5, 1, { 0, 0, 0, 0 } },	// ovr_16_0ea3_room_22_-_parlor___teleport.asm:376
	{  168,  42,  185,  54,  9, 20,  1, 1, { 0, 0, 0, 0 } },	// ovr_16_0ea3_room_22_-_parlor___teleport.asm:387
	{  157,  86,  183, 106, 10, 30,  1, 1, { 0, 0, 0, 0 } },	// ovr_16_0ea3_room_22_-_parlor___teleport.asm:398
	{  107,  56,  168, 121,  1,  1,  6, 1, { 0, 0, 0, 0 } },	// ovr_17_0e9f_room_23_-_crossroads.asm:179
	{  169,   0,  206, 115,  2,  2,  5, 1, { 0, 0, 0, 0 } },	// ovr_17_0e9f_room_23_-_crossroads.asm:187
	{  150,   0,  168,  78,  2,  2,  5, 1, { 0, 0, 0, 0 } },	// ovr_17_0e9f_room_23_-_crossroads.asm:195
	{    0,   0,   19, 159,  3,  3,  5, 1, { 0, 0, 0, 0 } },	// ovr_17_0e9f_room_23_-_crossroads.asm:203
	{  100,   0,  319, 122,  1,  3,  5, 1, { 1, 0, 0, 0 } },	// ovr_19_0e8f_room_25_-_park___mailbox.asm:260
	{  208, 123,  319, 159,  1,  3,  5, 1, { 1, 0, 0, 0 } },	// ovr_19_0e8f_room_25_-_park___mailbox.asm:268
	{  100,  72,  124, 122,  2,  1,  5, 1, { 6, 0, 0, 0 } },	// ovr_19_0e8f_room_25_-_park___mailbox.asm:278
	{  100,  72,  124, 122,  3,  2,  5, 1, { 9, 0, 0, 0 } },	// ovr_19_0e8f_room_25_-_park___mailbox.asm:287
	{    0,   0,   29, 127,  5,  6,  5, 1, { 0, 0, 0, 0 } },	// ovr_19_0e8f_room_25_-_park___mailbox.asm:312
	{   30,   0,   61, 106,  5,  6,  5, 1, { 0, 0, 0, 0 } },	// ovr_19_0e8f_room_25_-_park___mailbox.asm:320
	{   65, 147,  141, 159,  6,  7,  5, 1, { 0, 0, 0, 0 } },	// ovr_19_0e8f_room_25_-_park___mailbox.asm:328
	{  119, 109,  167, 144,  1,  2,  5, 1, { 14, 0, 0, 0 } },	// ovr_1a_0eaf_room_26_-_forest.asm:267
	{   94,  96,  118, 128,  2,  3,  5, 1, { 13, 0, 0, 0 } },	// ovr_1a_0eaf_room_26_-_forest.asm:275
	{  119,  97,  131, 118,  2,  3,  5, 1, { 13, 0, 0, 0 } },	// ovr_1a_0eaf_room_26_-_forest.asm:283
	{   83,  98,   93, 121,  2,  3,  5, 1, { 13, 0, 0, 0 } },	// ovr_1a_0eaf_room_26_-_forest.asm:291
	{  215,  47,  319, 131,  3,  4,  5, 1, { 0, 0, 0, 0 } },	// ovr_1a_0eaf_room_26_-_forest.asm:299
	{  101,  34,  133,  89,  4,  5,  5, 2, { 1, 2, 0, 0 } },	// ovr_1a_0eaf_room_26_-_forest.asm:309
	{  150,  28,  209,  65,  5,  8,  5, 1, { 3, 0, 0, 0 } },	// ovr_1a_0eaf_room_26_-_forest.asm:317
	{  147,  47,  192,  93,  6,  6,  5, 1, { 27, 0, 0, 0 } },	// ovr_1a_0eaf_room_26_-_forest.asm:328
	{  241,  18,  270,  49,  7, 15,  5, 1, { 11, 0, 0, 0 } },	// ovr_1a_0eaf_room_26_-_forest.asm:346
	{  195,  80,  219, 100,  9, 18,  1, 1, { 0, 0, 0, 0 } },	// ovr_1a_0eaf_room_26_-_forest.asm:372
	{  110, 108,  127, 124, 10, 20,  5, 1, { 0, 0, 0, 0 } },	// ovr_1a_0eaf_room_26_-_forest.asm:381
	{  107, 100,  124, 107, 12, 30,  5, 1, { 41, 0, 0, 0 } },	// ovr_1a_0eaf_room_26_-_forest.asm:398
	{  174,  13,  205,  23, 13, 31,  5, 1, { 43, 0, 0, 0 } },	// ovr_1a_0eaf_room_26_-_forest.asm:406
	{   77,   0,  140, 104,  1,  1,  5, 1, { 0, 0, 0, 0 } },	// ovr_1b_0e7f_room_27_-_mansion_exterior.asm:165
	{    0, 125,   78, 159,  2,  3,  5, 1, { 0, 0, 0, 0 } },	// ovr_1b_0e7f_room_27_-_mansion_exterior.asm:173
	{    9,  13,   56,  70,  3,  4,  5, 1, { 0, 0, 0, 0 } },	// ovr_1b_0e7f_room_27_-_mansion_exterior.asm:181
	{   39,  71,   71, 119,  3,  4,  5, 1, { 0, 0, 0, 0 } },	// ovr_1b_0e7f_room_27_-_mansion_exterior.asm:189
	{  165, 135,  199, 159,  4,  8,  5, 2, { 18, 19, 0, 0 } },	// ovr_1b_0e7f_room_27_-_mansion_exterior.asm:199
	{  103,   0,  179,  90,  1,  7,  5, 1, { 0, 0, 0, 0 } },	// ovr_1c_0eb7_room_28_-_telescope_room.asm:382
	{   22,  51,   86, 135,  2,  1,  5, 1, { 3, 0, 0, 0 } },	// ovr_1c_0eb7_room_28_-_telescope_room.asm:390
	{  145,  56,  233,  94,  4,  4, 10, 1, { 0, 0, 0, 0 } },	// ovr_1c_0eb7_room_28_-_telescope_room.asm:413
	{  190,  24,  293,  73,  4,  4, 10, 1, { 0, 0, 0, 0 } },	// ovr_1c_0eb7_room_28_-_telescope_room.asm:422
	{   71, 107,   85, 119,  5,  3,  5, 1, { 5, 0, 0, 0 } },	// ovr_1c_0eb7_room_28_-_telescope_room.asm:430
	{   71, 107,   85, 119,  6,  5,  1, 1, { 0, 0, 0, 0 } },	// ovr_1c_0eb7_room_28_-_telescope_room.asm:441
	{   44,  80,   58,  94,  7,  6, 13, 1, { 0, 0, 0, 0 } },	// ovr_1c_0eb7_room_28_-_telescope_room.asm:450
	{  226,  84,  249, 118,  8,  9, 13, 1, { 0, 0, 0, 0 } },	// ovr_1c_0eb7_room_28_-_telescope_room.asm:459
	{   44,  95,   58, 102,  9, 10,  5, 1, { 9, 0, 0, 0 } },	// ovr_1c_0eb7_room_28_-_telescope_room.asm:467
	{   44,  95,   58, 102, 10, 11,  1, 1, { 0, 0, 0, 0 } },	// ovr_1c_0eb7_room_28_-_telescope_room.asm:478
	{   73,  13,  168, 116,  1,  1,  5, 1, { 0, 0, 0, 0 } },	// ovr_1f_0e87_room_31_-_cliff.asm:223
	{    0,   0,   21, 159,  2,  2,  5, 1, { 0, 0, 0, 0 } },	// ovr_1f_0e87_room_31_-_cliff.asm:231
	{  120, 141,  319, 159,  2,  3,  5, 1, { 0, 0, 0, 0 } },	// ovr_1f_0e87_room_31_-_cliff.asm:239
	{  364,  31,  409, 115,  1,  1,  5, 1, { 15, 0, 0, 0 } },	// ovr_20_0e8b_room_32_-_cemetery.asm:238
	{  364,  64,  377,  86,  3,  3, 11, 1, { 6, 0, 0, 0 } },	// ovr_20_0e8b_room_32_-_cemetery.asm:285
	{  254,  67,  283, 108,  5,  5,  5, 1, { 25, 0, 0, 0 } },	// ovr_20_0e8b_room_32_-_cemetery.asm:307
	{  212,  69,  233,  90,  5,  6,  5, 1, { 24, 0, 0, 0 } },	// ovr_20_0e8b_room_32_-_cemetery.asm:315
	{    0,  70,   19, 160,  6,  8,  5, 1, { 0, 0, 0, 0 } },	// ovr_20_0e8b_room_32_-_cemetery.asm:323
	{  131,  75,  145,  87,  2,  3,  5, 1, { 3, 0, 0, 0 } },	// ovr_21_0e97_room_33_-_town.asm:172
	{  203,   0,  319, 119,  3,  2,  5, 1, { 0, 0, 0, 0 } },	// ovr_21_0e97_room_33_-_town.asm:180
	{    0,   0,   50, 105,  2,  1,  5, 1, { 0, 0, 0, 0 } },	// ovr_22_0e93_room_34_-_hippie___pal_area.asm:263
	{  113,  51,  149, 123,  3,  2,  6, 1, { 0, 0, 0, 0 } },	// ovr_22_0e93_room_34_-_hippie___pal_area.asm:274
	{   96, 139,  201, 159,  4,  5,  5, 1, { 0, 0, 0, 0 } },	// ovr_22_0e93_room_34_-_hippie___pal_area.asm:282
	{  145,  18,  165,  55,  1,  5,  5, 1, { 2, 0, 0, 0 } },	// ovr_23_0e7b_room_35_-_sewer.asm:233
	{  158,  42,  302,  57,  1,  5,  5, 1, { 2, 0, 0, 0 } },	// ovr_23_0e7b_room_35_-_sewer.asm:241
	{  279,  16,  292,  83,  1,  5,  5, 1, { 2, 0, 0, 0 } },	// ovr_23_0e7b_room_35_-_sewer.asm:249
	{  170,  81,  183, 130,  1,  5,  5, 1, { 2, 0, 0, 0 } },	// ovr_23_0e7b_room_35_-_sewer.asm:257
	{  179,  82,  239,  96,  1,  5,  5, 1, { 2, 0, 0, 0 } },	// ovr_23_0e7b_room_35_-_sewer.asm:265
	{   16,  18,   42, 136,  1,  6,  5, 1, { 2, 0, 0, 0 } },	// ovr_23_0e7b_room_35_-_sewer.asm:273
	{    0,  76,   16,  91,  1,  6,  5, 1, { 2, 0, 0, 0 } },	// ovr_23_0e7b_room_35_-_sewer.asm:281
	{  260,  96,  278, 113,  3,  1,  1, 1, { 1, 0, 0, 0 } },	// ovr_23_0e7b_room_35_-_sewer.asm:314
	{  136, 112,  145, 125,  4,  2, 12, 1, { 0, 0, 0, 0 } },	// ovr_23_0e7b_room_35_-_sewer.asm:325
	{   74,  19,  110, 116,  5,  3, 10, 1, { 0, 0, 0, 0 } },	// ovr_23_0e7b_room_35_-_sewer.asm:336
	{  170,  81,  188,  98,  7, 10, 10, 1, { 0, 0, 0, 0 } },	// ovr_23_0e7b_room_35_-_sewer.asm:358
	{    0, 100,   73, 159,  1,  2,  5, 1, { 0, 0, 0, 0 } },	// ovr_28_0ebb_room_40_-_cave_entrance.asm:214
	{   74, 100,   93, 135,  1,  2,  5, 1, { 0, 0, 0, 0 } },	// ovr_28_0ebb_room_40_-_cave_entrance.asm:222
	{  121, 111,  176, 159,  1,  4,  5, 1, { 0, 0, 0, 0 } },	// ovr_28_0ebb_room_40_-_cave_entrance.asm:230
	{  226,   0,  319, 122,  1,  3,  5, 1, { 0, 0, 0, 0 } },	// ovr_28_0ebb_room_40_-_cave_entrance.asm:238
	{  254, 123,  319, 137,  1,  3,  5, 1, { 0, 0, 0, 0 } },	// ovr_28_0ebb_room_40_-_cave_entrance.asm:246
	{  174,  71,  212, 145,  2, 10,  6, 1, { 0, 0, 0, 0 } },	// ovr_28_0ebb_room_40_-_cave_entrance.asm:257
	{   65,  55,   95,  96,  1,  1,  5, 1, { 19, 0, 0, 0 } },	// ovr_29_0f89_room_41_-_shore___underwater_entry.asm:378
	{   83, 112,  214, 159,  3,  3,  5, 1, { 18, 0, 0, 0 } },	// ovr_29_0f89_room_41_-_shore___underwater_entry.asm:400
	{  215, 119,  232, 159,  3,  3,  5, 1, { 18, 0, 0, 0 } },	// ovr_29_0f89_room_41_-_shore___underwater_entry.asm:408
	{  233, 123,  257, 159,  3,  3,  5, 1, { 18, 0, 0, 0 } },	// ovr_29_0f89_room_41_-_shore___underwater_entry.asm:416
	{   63, 127,   82, 159,  3,  3,  5, 1, { 18, 0, 0, 0 } },	// ovr_29_0f89_room_41_-_shore___underwater_entry.asm:424
	{   18,  24,   37,  48,  4,  5,  5, 1, { 15, 0, 0, 0 } },	// ovr_29_0f89_room_41_-_shore___underwater_entry.asm:432
	{  124,  45,  159,  57,  6,  8,  5, 1, { 17, 0, 0, 0 } },	// ovr_29_0f89_room_41_-_shore___underwater_entry.asm:453
	{  133,  27,  150,  49,  7,  6,  5, 1, { 15, 0, 0, 0 } },	// ovr_29_0f89_room_41_-_shore___underwater_entry.asm:461
	{   62,  44,  129,  55,  8,  9,  5, 1, { 16, 0, 0, 0 } },	// ovr_29_0f89_room_41_-_shore___underwater_entry.asm:471
	{    6,  22,   45, 111,  1,  2,  5, 1, { 1, 0, 0, 0 } },	// ovr_2d_0f8d_rooms_43_44_45_-_maze_+_crystal_entry.asm:241
	{   40,  54,   67,  81,  2,  8,  5, 1, { 17, 0, 0, 0 } },	// ovr_2d_0f8d_rooms_43_44_45_-_maze_+_crystal_entry.asm:259
	{   70,  21,  126, 115,  3,  3,  5, 1, { 1, 0, 0, 0 } },	// ovr_2d_0f8d_rooms_43_44_45_-_maze_+_crystal_entry.asm:272
	{  147,  55,  164,  91,  4,  1,  5, 3, { 2, 3, 4, 0 } },	// ovr_2d_0f8d_rooms_43_44_45_-_maze_+_crystal_entry.asm:288
	{  200,  27,  254, 110,  3,  4,  5, 1, { 1, 0, 0, 0 } },	// ovr_2d_0f8d_rooms_43_44_45_-_maze_+_crystal_entry.asm:301
	{  274,  35,  319, 122,  3,  5,  5, 1, { 1, 0, 0, 0 } },	// ovr_2d_0f8d_rooms_43_44_45_-_maze_+_crystal_entry.asm:314
	{   64, 134,  127, 159,  6,  6,  5, 1, { 11, 0, 0, 0 } },	// ovr_2d_0f8d_rooms_43_44_45_-_maze_+_crystal_entry.asm:327
	{  192, 134,  255, 159,  6,  7,  5, 1, { 12, 0, 0, 0 } },	// ovr_2d_0f8d_rooms_43_44_45_-_maze_+_crystal_entry.asm:340
	{    6,  22,   45, 111,  1,  2,  5, 1, { 1, 0, 0, 0 } },	// ovr_2d_0f8d_rooms_43_44_45_-_maze_+_crystal_entry.asm:368
	{   40,  54,   67,  81,  2,  8,  5, 1, { 17, 0, 0, 0 } },	// ovr_2d_0f8d_rooms_43_44_45_-_maze_+_crystal_entry.asm:386
	{   70,  21,  126, 115,  1,  3,  5, 1, { 1, 0, 0, 0 } },	// ovr_2d_0f8d_rooms_43_44_45_-_maze_+_crystal_entry.asm:399
	{  147,  55,  164,  91,  3,  1,  5, 3, { 2, 3, 4, 0 } },	// ovr_2d_0f8d_rooms_43_44_45_-_maze_+_crystal_entry.asm:415
	{  200,  27,  254, 110,  1,  4,  5, 1, { 1, 0, 0, 0 } },	// ovr_2d_0f8d_rooms_43_44_45_-_maze_+_crystal_entry.asm:428
	{  274,  35,  319, 122,  1,  5,  5, 1, { 1, 0, 0, 0 } },	// ovr_2d_0f8d_rooms_43_44_45_-_maze_+_crystal_entry.asm:441
	{  251,  76,  304, 126,  4, 10,  5, 4, { 14, 24, 25, 26 } },	// ovr_2d_0f8d_rooms_43_44_45_-_maze_+_crystal_entry.asm:458
	{  259,  57,  291,  88,  5, 11,  1, 1, { 0, 0, 0, 0 } },	// ovr_2d_0f8d_rooms_43_44_45_-_maze_+_crystal_entry.asm:469
	{  262,  89,  273,  97,  6, 20,  5, 1, { 20, 0, 0, 0 } },	// ovr_2d_0f8d_rooms_43_44_45_-_maze_+_crystal_entry.asm:477
	{   64, 134,  127, 159,  7,  6,  5, 1, { 11, 0, 0, 0 } },	// ovr_2d_0f8d_rooms_43_44_45_-_maze_+_crystal_entry.asm:490
	{  192, 134,  255, 159,  7,  7,  5, 1, { 12, 0, 0, 0 } },	// ovr_2d_0f8d_rooms_43_44_45_-_maze_+_crystal_entry.asm:503
	{  269,  83,  319, 133,  1,  1,  3, 1, { 1, 0, 0, 0 } },	// ovr_xx_0ec3_room_46_-_diving_area___underwater.asm:168
	{  269,  83,  319, 133,  1,  2,  5, 1, { 3, 0, 0, 0 } },	// ovr_xx_0ec3_room_46_-_diving_area___underwater.asm:177
	{    0,  29,   66, 138,  2,  4,  5, 1, { 21, 0, 0, 0 } },	// ovr_xx_0ec3_room_46_-_diving_area___underwater.asm:185
	{    0,  29,   66, 138,  2,  5,  5, 1, { 22, 0, 0, 0 } },	// ovr_xx_0ec3_room_46_-_diving_area___underwater.asm:195
	{   90, 142,  231, 159,  1,  1,  5, 1, { 1, 0, 0, 0 } },	// ovr_30_0ebf_room_48_-_alien_ship_upper_level.asm:164
	{  101, 124,  176, 141,  1,  1,  5, 1, { 1, 0, 0, 0 } },	// ovr_30_0ebf_room_48_-_alien_ship_upper_level.asm:172
	{    0,   0,   41, 111,  2,  2,  3, 1, { 7, 0, 0, 0 } },	// ovr_30_0ebf_room_48_-_alien_ship_upper_level.asm:183
	{    0,   0,   41, 111,  2,  6,  5, 1, { 13, 0, 0, 0 } },	// ovr_30_0ebf_room_48_-_alien_ship_upper_level.asm:192
	{   77,  27,  100,  60,  3,  3,  5, 1, { 4, 0, 0, 0 } },	// ovr_30_0ebf_room_48_-_alien_ship_upper_level.asm:200
	{  153,   0,  225, 109,  4,  4,  5, 1, { 3, 0, 0, 0 } },	// ovr_30_0ebf_room_48_-_alien_ship_upper_level.asm:208
	{  177, 110,  231, 141,  5,  5,  5, 1, { 5, 0, 0, 0 } },	// ovr_30_0ebf_room_48_-_alien_ship_upper_level.asm:216
	{   82,  17,  106,  92,  1,  1,  5, 1, { 0, 0, 0, 0 } },	// ovr_31_0f85_room_49_-_engine_room.asm:172
	{  245,  67,  262,  92,  3,  3, 13, 1, { 0, 0, 0, 0 } },	// ovr_31_0f85_room_49_-_engine_room.asm:196
	{  117,  61,  129,  76,  4,  4, 12, 1, { 0, 0, 0, 0 } },	// ovr_31_0f85_room_49_-_engine_room.asm:205
	{   57,  96,   73, 113,  5,  5,  5, 1, { 6, 0, 0, 0 } },	// ovr_31_0f85_room_49_-_engine_room.asm:213
	{   69, 133,  132, 160,  1,  1,  5, 1, { 9, 0, 0, 0 } },	// ovr_32_0f81_room_50_-_steam_room.asm:188
	{   34,   0,   62,  67,  2,  3,  5, 1, { 10, 0, 0, 0 } },	// ovr_32_0f81_room_50_-_steam_room.asm:196
	{   31,  68,  112, 108,  3,  4,  5, 1, { 11, 0, 0, 0 } },	// ovr_32_0f81_room_50_-_steam_room.asm:204
	{  226,  60,  302, 158,  4,  2,  5, 1, { 1, 0, 0, 0 } },	// ovr_32_0f81_room_50_-_steam_room.asm:214
	{  234, 119,  281, 154,  5,  5,  5, 1, { 4, 0, 0, 0 } },	// ovr_32_0f81_room_50_-_steam_room.asm:224
	{  271,  91,  295, 115,  6,  6, 13, 1, { 0, 0, 0, 0 } },	// ovr_32_0f81_room_50_-_steam_room.asm:233
	{   51,  56,   93, 119,  1,  1,  5, 1, { 3, 0, 0, 0 } },	// ovr_33_0faa_room_51_-_alien_lobby.asm:147
	{  280,  54,  307, 123,  1,  2,  5, 1, { 3, 0, 0, 0 } },	// ovr_33_0faa_room_51_-_alien_lobby.asm:155
	{   20,  40,   43,  58,  2,  3,  5, 1, { 1, 0, 0, 0 } },	// ovr_33_0faa_room_51_-_alien_lobby.asm:163
	{  175,  15,  199,  37,  2,  4,  5, 1, { 1, 0, 0, 0 } },	// ovr_33_0faa_room_51_-_alien_lobby.asm:171
	{   27,  44,   55, 132,  1,  1,  5, 1, { 1, 0, 0, 0 } },	// ovr_xx_0f96_room_52_-_security_scanner.asm:169
	{  143,  62,  203,  83,  2,  2,  5, 1, { 2, 0, 0, 0 } },	// ovr_xx_0f96_room_52_-_security_scanner.asm:177
	{  581,  44,  599, 130,  1,  3,  5, 1, { 3, 0, 0, 0 } },	// ovr_xx_0f96_room_52_-_security_scanner.asm:185
	{  238,  43,  292, 135,  3,  5,  5, 1, { 8, 0, 0, 0 } },	// ovr_xx_0f96_room_52_-_security_scanner.asm:193
	{  293,  42,  489, 135,  3,  6,  5, 1, { 10, 0, 0, 0 } },	// ovr_xx_0f96_room_52_-_security_scanner.asm:201
	{  490,  42,  534, 135,  3,  4,  5, 1, { 7, 0, 0, 0 } },	// ovr_xx_0f96_room_52_-_security_scanner.asm:209
	{  278,  25,  306,  40,  4,  7,  5, 1, { 15, 0, 0, 0 } },	// ovr_xx_0f96_room_52_-_security_scanner.asm:217
	{  374,  25,  400,  41,  4,  8,  5, 1, { 15, 0, 0, 0 } },	// ovr_xx_0f96_room_52_-_security_scanner.asm:225
	{  467,  25,  493,  41,  4,  9,  5, 1, { 15, 0, 0, 0 } },	// ovr_xx_0f96_room_52_-_security_scanner.asm:233
	{  162,  38,  190,  57,  4, 20,  5, 1, { 15, 0, 0, 0 } },	// ovr_xx_0f96_room_52_-_security_scanner.asm:241
	{   15,  43,   43, 120,  1,  1,  5, 1, { 5, 0, 0, 0 } },	// ovr_36_0fa6_room_54_-_waiting_room.asm:370
	{   48,  72,   55,  79,  4, 12, 12, 1, { 0, 0, 0, 0 } },	// ovr_36_0fa6_room_54_-_waiting_room.asm:407
	{   36,  33,   87,  87,  5, 17,  5, 1, { 60, 0, 0, 0 } },	// ovr_36_0fa6_room_54_-_waiting_room.asm:417
	{  135,  32,  183,  57,  6,  4,  5, 1, { 8, 0, 0, 0 } },	// ovr_36_0fa6_room_54_-_waiting_room.asm:425
	{  279,  38,  305, 121,  7,  5,  5, 1, { 9, 0, 0, 0 } },	// ovr_36_0fa6_room_54_-_waiting_room.asm:433
	{  275,  14,  310,  43,  8,  6,  5, 1, { 10, 0, 0, 0 } },	// ovr_36_0fa6_room_54_-_waiting_room.asm:441
	{  238,  90,  260, 111,  9,  7,  5, 1, { 11, 0, 0, 0 } },	// ovr_36_0fa6_room_54_-_waiting_room.asm:451
	{  110,  76,  129, 102, 10,  9,  6, 1, { 15, 0, 0, 0 } },	// ovr_36_0fa6_room_54_-_waiting_room.asm:462
	{  185,  45,  227,  99, 10, 10,  6, 1, { 16, 0, 0, 0 } },	// ovr_36_0fa6_room_54_-_waiting_room.asm:473
	{  221,  90,  245, 122, 10, 10,  6, 1, { 16, 0, 0, 0 } },	// ovr_36_0fa6_room_54_-_waiting_room.asm:482
	{  244,  94,  256, 108, 11, 16,  5, 1, { 50, 0, 0, 0 } },	// ovr_36_0fa6_room_54_-_waiting_room.asm:490
	{  108,  13,  210,  26, 12, 11,  5, 1, { 7, 0, 0, 0 } },	// ovr_36_0fa6_room_54_-_waiting_room.asm:498
	{   60,  78,   71,  84, 13, 13,  1, 1, { 0, 0, 0, 0 } },	// ovr_36_0fa6_room_54_-_waiting_room.asm:509
	{  108,  88,  129, 103, 14, 14,  5, 1, { 32, 0, 0, 0 } },	// ovr_36_0fa6_room_54_-_waiting_room.asm:519
	{   79, 107,   85, 112, 15, 18,  1, 1, { 61, 0, 0, 0 } },	// ovr_36_0fa6_room_54_-_waiting_room.asm:530
	{  277,  51,  319, 142,  1,  1,  5, 1, { 3, 0, 0, 0 } },	// ovr_37_0f9a_room_55_-_corridor.asm:134
	{   63,  32,  104,  41,  3,  3,  5, 1, { 1, 0, 0, 0 } },	// ovr_37_0f9a_room_55_-_corridor.asm:164
	{  167,   0,  245, 101,  1,  1,  5, 1, { 9, 0, 0, 0 } },	// ovr_38_0f92_room_56_-_transporter_chamber.asm:247
	{  154,   0,  166,  98,  1,  1,  5, 1, { 9, 0, 0, 0 } },	// ovr_38_0f92_room_56_-_transporter_chamber.asm:255
	{  135,   0,  153,  92,  1,  1,  5, 1, { 9, 0, 0, 0 } },	// ovr_38_0f92_room_56_-_transporter_chamber.asm:263
	{   41,  27,   89,  97,  2,  2,  5, 1, { 0, 0, 0, 0 } },	// ovr_38_0f92_room_56_-_transporter_chamber.asm:271
	{   88, 104,  106, 118,  3,  7,  5, 1, { 0, 0, 0, 0 } },	// ovr_38_0f92_room_56_-_transporter_chamber.asm:279
	{   39, 111,   69, 146,  4,  3,  5, 1, { 1, 0, 0, 0 } },	// ovr_38_0f92_room_56_-_transporter_chamber.asm:290
	{   49,  90,  106, 127,  4,  3,  5, 1, { 1, 0, 0, 0 } },	// ovr_38_0f92_room_56_-_transporter_chamber.asm:298
	{    0, 124,   72, 159,  4,  4,  5, 1, { 2, 0, 0, 0 } },	// ovr_38_0f92_room_56_-_transporter_chamber.asm:309
	{   88, 104,  106, 118,  5,  8,  1, 1, { 0, 0, 0, 0 } },	// ovr_38_0f92_room_56_-_transporter_chamber.asm:320
	{   43,  88,   76, 105,  4,  5,  5, 1, { 3, 0, 0, 0 } },	// ovr_38_0f92_room_56_-_transporter_chamber.asm:331
	{   77,  92,   96, 120,  4,  5,  5, 1, { 3, 0, 0, 0 } },	// ovr_38_0f92_room_56_-_transporter_chamber.asm:339
	{   97,  95,  125, 132,  4,  5,  5, 1, { 3, 0, 0, 0 } },	// ovr_38_0f92_room_56_-_transporter_chamber.asm:347
	{   56,  40,  111, 114,  1,  2,  5, 1, { 0, 0, 0, 0 } },	// ovr_35_0f9e_rooms_53_57_-_hallways.asm:317
	{  171,  13,  237, 106,  8, 20,  5, 1, { 4, 0, 0, 0 } },	// ovr_35_0f9e_rooms_53_57_-_hallways.asm:328
	{  305,  13,  349,  63,  8, 21,  5, 1, { 4, 0, 0, 0 } },	// ovr_35_0f9e_rooms_53_57_-_hallways.asm:336
	{  371,  39,  412, 124,  2,  1,  5, 1, { 0, 0, 0, 0 } },	// ovr_35_0f9e_rooms_53_57_-_hallways.asm:344
	{  171,  13,  237, 106,  8, 20,  5, 1, { 15, 0, 0, 0 } },	// ovr_35_0f9e_rooms_53_57_-_hallways.asm:388
	{  305,  13,  346, 106,  8, 21,  5, 1, { 15, 0, 0, 0 } },	// ovr_35_0f9e_rooms_53_57_-_hallways.asm:396
	{  333,  46,  402, 128,  5,  3,  6, 1, { 0, 0, 0, 0 } },	// ovr_35_0f9e_rooms_53_57_-_hallways.asm:407
	{  396,  77,  416,  90,  7,  5,  5, 1, { 8, 0, 0, 0 } },	// ovr_35_0f9e_rooms_53_57_-_hallways.asm:431
	{  380,  95,  396, 112,  1,  3,  5, 1, { 4, 0, 0, 0 } },	// ovr_3a_101d_room_58_-_jail.asm:364
	{  380,  85,  404, 108,  2,  7,  5, 1, { 7, 0, 0, 0 } },	// ovr_3a_101d_room_58_-_jail.asm:383
	{   42,  82,  142, 130,  4, 11, 10, 2, { 11, 12, 0, 0 } },	// ovr_3a_101d_room_58_-_jail.asm:410
	{  593,  85,  600,  96,  5, 13,  5, 1, { 22, 0, 0, 0 } },	// ovr_3a_101d_room_58_-_jail.asm:418
	{  593,  85,  600,  96,  6, 14,  1, 1, { 21, 0, 0, 0 } },	// ovr_3a_101d_room_58_-_jail.asm:429
	{  364,  25,  501, 128,  8, 16,  5, 1, { 69, 0, 0, 0 } },	// ovr_3a_101d_room_58_-_jail.asm:454
	{  195,  26,  332, 127,  8, 17,  5, 1, { 68, 0, 0, 0 } },	// ovr_3a_101d_room_58_-_jail.asm:464
	{  289,  65,  320, 112,  9,  5,  6, 1, { 0, 0, 0, 0 } },	// ovr_3a_101d_room_58_-_jail.asm:482
	{   17,  83,   24,  92, 12, 21,  5, 1, { 83, 0, 0, 0 } },	// ovr_3a_101d_room_58_-_jail.asm:520
	{   25,  70,   47, 134,  1,  1,  5, 1, { 4, 0, 0, 0 } },	// ovr_3b_0fa2_room_59_-_escape_pod.asm:215
	{   90,  52,  116,  73,  2,  2,  5, 1, { 2, 0, 0, 0 } },	// ovr_3b_0fa2_room_59_-_escape_pod.asm:223
	{    1,  69,   16,  88,  2,  3,  5, 1, { 1, 0, 0, 0 } },	// ovr_3b_0fa2_room_59_-_escape_pod.asm:231
	{   21,  30,   52,  64,  3,  4,  5, 1, { 3, 0, 0, 0 } },	// ovr_3b_0fa2_room_59_-_escape_pod.asm:239
	{  145,  54,  228, 122,  4,  5,  5, 1, { 16, 0, 0, 0 } },	// ovr_3b_0fa2_room_59_-_escape_pod.asm:247
	{  228,  84,  308, 152,  5,  6,  5, 1, { 6, 0, 0, 0 } },	// ovr_3b_0fa2_room_59_-_escape_pod.asm:255
	{  112,  88,  128,  98,  6,  7,  5, 1, { 8, 0, 0, 0 } },	// ovr_3b_0fa2_room_59_-_escape_pod.asm:263
};

// Room number, first hotspot, count. Rooms are in ascending order so the
// lookup can stop early; rooms with no decoded hotspot are absent.
struct HotspotRoom {
	byte room;
	uint16 first;
	uint16 count;
};

static const HotspotRoom kHotspotRooms[] = {
	{  3,   0, 15 },
	{  6,  15,  7 },
	{  7,  22, 20 },
	{  8,  42, 19 },
	{ 10,  61, 17 },
	{ 11,  78,  6 },
	{ 13,  84, 11 },
	{ 14,  95,  7 },
	{ 15, 102,  3 },
	{ 17, 105,  1 },
	{ 18, 106, 18 },
	{ 19, 124, 12 },
	{ 21, 136, 11 },
	{ 22, 147, 10 },
	{ 23, 157,  4 },
	{ 25, 161,  7 },
	{ 26, 168, 13 },
	{ 27, 181,  5 },
	{ 28, 186, 10 },
	{ 31, 196,  3 },
	{ 32, 199,  5 },
	{ 33, 204,  2 },
	{ 34, 206,  3 },
	{ 35, 209, 11 },
	{ 40, 220,  6 },
	{ 41, 226,  9 },
	{ 43, 235, 19 },
	{ 46, 254,  4 },
	{ 48, 258,  7 },
	{ 49, 265,  4 },
	{ 50, 269,  6 },
	{ 51, 275,  4 },
	{ 52, 279, 10 },
	{ 54, 289, 15 },
	{ 55, 304,  2 },
	{ 56, 306, 12 },
	{ 57, 318,  8 },
	{ 58, 326,  9 },
	{ 59, 335,  7 },
};

const Hotspot *hotspotsForRoom(int room, uint &count) {
	count = 0;
	for (uint i = 0; i < ARRAYSIZE(kHotspotRooms); i++) {
		if (kHotspotRooms[i].room != room)
			continue;
		count = kHotspotRooms[i].count;
		return &kHotspots[kHotspotRooms[i].first];
	}
	return nullptr;
}

} // End of namespace Alien
