/* ScummVM - Graphic Adventure Engine
 *
 * ScummVM is the legal property of its developers, whose names
 * are too numerous to list here. Please refer to the COPYRIGHT
 * file distributed with this source distribution.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

// Generated by tools/gen_maze.py of the Alien Incident reverse engineering
// repository -- do not edit by hand.
//
// The two mazes, out of the four tables data segment 271a packs end to end:
// tiles at 0x6450 and neighbours at 0x654b for room 43, tiles at 0x65dc and
// neighbours at 0x666f for room 44. A tile byte says which of the three MAZBLK
// plates that piece of the corridor is copied from -- 0 a wall, 1 an opening,
// 2 a decor block -- and an opening is also what registers that direction's
// rectangle. A neighbour byte is the cell that direction leads to, or 0xff.
//
//   36 cells in room 43, 21 in room 44.

#include "alien/mazetables.h"

namespace Alien {

static const MazeCell kMazeCellsA[] = {
	{ { 2, 0, 1, 1, 0, 0, 1 }, { 0x01, 0xff, 0xff, 0xff } },	// cell 0x00
	{ { 1, 0, 0, 0, 0, 0, 1 }, { 0xff, 0xff, 0x00, 0x02 } },	// cell 0x01
	{ { 1, 0, 1, 1, 1, 0, 0 }, { 0x06, 0x01, 0xff, 0x03 } },	// cell 0x02
	{ { 1, 0, 0, 0, 1, 0, 0 }, { 0xff, 0x02, 0xff, 0x04 } },	// cell 0x03
	{ { 0, 1, 1, 0, 1, 0, 0 }, { 0x05, 0x03, 0xff, 0xff } },	// cell 0x04
	{ { 0, 2, 1, 0, 0, 1, 0 }, { 0xff, 0xff, 0x04, 0xff } },	// cell 0x05
	{ { 0, 1, 0, 0, 0, 0, 1 }, { 0x07, 0xff, 0x02, 0xff } },	// cell 0x06
	{ { 0, 0, 0, 1, 1, 1, 0 }, { 0x0c, 0x08, 0x06, 0xff } },	// cell 0x07
	{ { 1, 1, 0, 1, 1, 0, 0 }, { 0x0d, 0x09, 0xff, 0x07 } },	// cell 0x08
	{ { 1, 0, 0, 0, 1, 0, 0 }, { 0xff, 0x0a, 0xff, 0x08 } },	// cell 0x09
	{ { 1, 0, 0, 0, 0, 1, 1 }, { 0xff, 0xff, 0x0b, 0x09 } },	// cell 0x0a
	{ { 0, 1, 1, 1, 0, 0, 0 }, { 0x0a, 0xff, 0xff, 0xff } },	// cell 0x0b
	{ { 1, 0, 0, 0, 0, 0, 1 }, { 0xff, 0x0d, 0x07, 0x14 } },	// cell 0x0c
	{ { 0, 1, 0, 0, 0, 1, 1 }, { 0x0e, 0xff, 0x08, 0x0c } },	// cell 0x0d
	{ { 0, 1, 1, 1, 1, 1, 0 }, { 0x0f, 0x15, 0x0d, 0xff } },	// cell 0x0e
	{ { 1, 1, 1, 0, 0, 1, 1 }, { 0x18, 0xff, 0x0e, 0x10 } },	// cell 0x0f
	{ { 1, 0, 1, 0, 1, 0, 0 }, { 0xff, 0x0f, 0xff, 0x11 } },	// cell 0x10
	{ { 1, 0, 0, 0, 1, 0, 1 }, { 0xff, 0x10, 0x13, 0x12 } },	// cell 0x11
	{ { 0, 0, 1, 0, 1, 0, 0 }, { 0xff, 0x11, 0xff, 0xff } },	// cell 0x12
	{ { 0, 0, 1, 1, 0, 1, 0 }, { 0x11, 0xff, 0x14, 0xff } },	// cell 0x13
	{ { 0, 1, 0, 0, 1, 0, 0 }, { 0x13, 0x0c, 0xff, 0xff } },	// cell 0x14
	{ { 1, 0, 0, 0, 1, 0, 0 }, { 0xff, 0x16, 0xff, 0x0e } },	// cell 0x15
	{ { 1, 0, 1, 1, 0, 0, 0 }, { 0x17, 0xff, 0xff, 0x15 } },	// cell 0x16
	{ { 0, 0, 0, 0, 0, 0, 1 }, { 0xff, 0xff, 0x16, 0xff } },	// cell 0x17
	{ { 0, 0, 0, 1, 0, 1, 0 }, { 0x19, 0xff, 0x0f, 0xff } },	// cell 0x18
	{ { 1, 1, 0, 0, 0, 0, 1 }, { 0x1b, 0xff, 0x18, 0x1a } },	// cell 0x19
	{ { 0, 0, 1, 0, 1, 0, 0 }, { 0xff, 0x19, 0xff, 0xff } },	// cell 0x1a
	{ { 0, 1, 1, 1, 1, 1, 0 }, { 0x1d, 0x1c, 0x19, 0xff } },	// cell 0x1b
	{ { 1, 0, 1, 0, 1, 0, 0 }, { 0xff, 0x22, 0xff, 0x1b } },	// cell 0x1c
	{ { 0, 0, 0, 1, 0, 1, 1 }, { 0x1e, 0xff, 0x1b, 0xff } },	// cell 0x1d
	{ { 0, 0, 1, 0, 1, 0, 1 }, { 0xff, 0x1f, 0x1d, 0xff } },	// cell 0x1e
	{ { 1, 0, 0, 0, 1, 0, 0 }, { 0xff, 0x20, 0xff, 0x1e } },	// cell 0x1f
	{ { 1, 0, 0, 0, 0, 1, 1 }, { 0xff, 0xff, 0x21, 0x1f } },	// cell 0x20
	{ { 0, 1, 1, 1, 0, 1, 0 }, { 0x20, 0xff, 0x22, 0xff } },	// cell 0x21
	{ { 1, 1, 0, 0, 0, 0, 1 }, { 0x21, 0xff, 0x23, 0x1c } },	// cell 0x22
	{ { 0, 0, 1, 1, 0, 0, 0 }, { 0x22, 0xff, 0xff, 0xff } },	// cell 0x23
};

static const MazeCell kMazeCellsB[] = {
	{ { 0, 1, 1, 0, 0, 1, 0 }, { 0x01, 0xff, 0xff, 0xff } },	// cell 0x00
	{ { 1, 0, 0, 0, 1, 1, 0 }, { 0xff, 0x05, 0x00, 0x02 } },	// cell 0x01
	{ { 0, 1, 0, 1, 1, 0, 0 }, { 0x03, 0x01, 0xff, 0xff } },	// cell 0x02
	{ { 0, 1, 0, 0, 0, 1, 1 }, { 0x04, 0xff, 0x02, 0xff } },	// cell 0x03
	{ { 0, 0, 1, 0, 0, 1, 0 }, { 0xff, 0xff, 0x03, 0xff } },	// cell 0x04
	{ { 1, 1, 1, 0, 0, 0, 0 }, { 0x06, 0xff, 0xff, 0x01 } },	// cell 0x05
	{ { 1, 0, 0, 1, 0, 1, 0 }, { 0x08, 0xff, 0x05, 0x07 } },	// cell 0x06
	{ { 0, 0, 1, 0, 1, 0, 0 }, { 0xff, 0x06, 0xff, 0xff } },	// cell 0x07
	{ { 0, 1, 1, 0, 0, 0, 1 }, { 0x09, 0xff, 0x06, 0xff } },	// cell 0x08
	{ { 1, 0, 0, 1, 0, 1, 0 }, { 0x0f, 0xff, 0x08, 0x0a } },	// cell 0x09
	{ { 1, 0, 1, 0, 1, 0, 0 }, { 0xff, 0x09, 0xff, 0x0b } },	// cell 0x0a
	{ { 1, 0, 1, 0, 1, 0, 0 }, { 0xff, 0x0a, 0xff, 0x0c } },	// cell 0x0b
	{ { 1, 1, 0, 0, 1, 0, 0 }, { 0x13, 0x0b, 0xff, 0x0d } },	// cell 0x0c
	{ { 0, 0, 1, 0, 1, 1, 1 }, { 0xff, 0x0c, 0x0e, 0xff } },	// cell 0x0d
	{ { 0, 1, 1, 1, 0, 0, 1 }, { 0x0d, 0xff, 0xff, 0xff } },	// cell 0x0e
	{ { 1, 0, 1, 0, 1, 0, 1 }, { 0xff, 0x11, 0x09, 0x10 } },	// cell 0x0f
	{ { 2, 0, 1, 0, 1, 0, 0 }, { 0xff, 0x0f, 0xff, 0xff } },	// cell 0x10
	{ { 1, 1, 0, 0, 0, 0, 0 }, { 0x12, 0xff, 0xff, 0x0f } },	// cell 0x11
	{ { 2, 0, 1, 2, 2, 1, 0 }, { 0xff, 0xff, 0x11, 0xff } },	// cell 0x12
	{ { 1, 0, 0, 0, 0, 1, 0 }, { 0xff, 0xff, 0x0c, 0x14 } },	// cell 0x13
	{ { 0, 0, 1, 0, 1, 0, 0 }, { 0xff, 0x13, 0xff, 0xff } },	// cell 0x14
};

const MazeCell *mazeCells(int room, uint &count) {
	switch (room) {
	case 43:
		count = ARRAYSIZE(kMazeCellsA);
		return kMazeCellsA;
	case 44:
		count = ARRAYSIZE(kMazeCellsB);
		return kMazeCellsB;
	default:
		count = 0;
		return nullptr;
	}
}

} // End of namespace Alien
