/* ScummVM - Graphic Adventure Engine
 *
 * ScummVM is the legal property of its developers, whose names
 * are too numerous to list here. Please refer to the COPYRIGHT
 * file distributed with this source distribution.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

// Generated by tools/gen_occlusion.py of the Alien Incident reverse engineering
// repository -- do not edit by hand.
//
// The foreground rectangles that hide the character: 67 of them across
// 30 rooms, lifted from every OBJ:sub_03400 call site in the scene
// overlays.

#include "alien/occlusion.h"

namespace Alien {

// The flag guards a room's tick puts on a rectangle, in rectangle order.
static const ScriptCond kOcclusionGuards[] = {
	{ 0xa6fa,   1, false },
	{ 0xa6fa,   0, false },
	{ 0xa73a,   1, false },
	{ 0xa785,   0, false },
	{ 0xa785,   1, false },
	{ 0xa78a,   1, false },
	{ 0xa785,   1, false },
	{ 0xa785,   1, false },
};

// Every rectangle, grouped by room and in the order its room's tick draws them.
static const OcclusionRect kOcclusionRects[] = {
	{  3, 100,  14, 100,  14, 220, 142,   -1,   0, 0 },
	{  3,   0,  52, 320,  52,  78, 104,   -1,   0, 0 },
	{  3,   0, 157,   0,  91, 100,  42,   63,   0, 0 },
	{  6, 126,  69, 126,  69, 194,  70,   73,   0, 0 },
	{  6,   0, 147,   0, 108, 137,  47,   -1,   0, 0 },
	{  6,  56,  32,  56,  32,  52,  86,   41,   0, 0 },
	{  7,   0,  94,   0,  94, 274,  61,   -1,   0, 0 },
	{  7, 274,  21, 274,  21,  46, 134,   -1,   0, 0 },
	{  7, 121,  32,  98,  65,  58,  48,   45,   0, 1 },
	{  7,  99,  28,  82,  66,  74,  52,   45,   1, 1 },
	{ 10,  17, 126,   0,  81, 302,  74,   -1,   2, 0 },
	{ 15, 198,  41, 518,  41, 122, 114,   -1,   2, 0 },
	{ 15,   0,   9,   0,   9,  60, 166,   -1,   2, 0 },
	{ 17,  83,  50,  83,  50, 197, 105,   -1,   2, 0 },
	{ 18,   0,   0,  29,  93, 263,  64,   -1,   2, 0 },
	{ 18,   0,  66,  30, 112,  40,  39,   79,   2, 0 },
	{ 19,   0,   0, 162, 124, 104,  31,   -1,   2, 0 },
	{ 19, 105,   0, 140,  47,  54,  66,   42,   2, 0 },
	{ 19, 169,   0, 243,  43,  51,  78,   57,   2, 0 },
	{ 21,   2,  14, 187, 143,  58,  12,   -1,   2, 0 },
	{ 21,   3,  35, 301,  33, 317, 122,   -1,   2, 0 },
	{ 22,   0,   0,   0,  44, 108, 114,   -1,   2, 0 },
	{ 22,   0, 115,  92, 119,  87,  39,   -1,   2, 0 },
	{ 22,  54, 155, 225, 123,  62,  35,   -1,   2, 0 },
	{ 22, 121, 149, 225,  51,  62,  14,   -1,   2, 0 },
	{ 22, 110,   0, 189,  22,  36, 124,   -1,   2, 0 },
	{ 22, 155,   0, 287,  14, 138, 132,   -1,   2, 0 },
	{ 23,   0,  34,   0,  34, 125, 122,   73,   2, 0 },
	{ 23, 188,  98, 188,  98, 132,  57,   -1,   2, 0 },
	{ 25,   0,  33,   0,  33,  83, 108,   77,   2, 0 },
	{ 25, 113,  15, 113,  15,  94, 114,   73,   2, 0 },
	{ 26,   0,   0,  52,  97, 105,  47,   72,   2, 0 },
	{ 26, 123,   0, 188,  38, 132, 120,   79,   2, 0 },
	{ 28,   0,   0, 118,  13,  50, 142,   -1,   2, 0 },
	{ 28, 243,  75, 243,  75,  77,  80,   -1,   2, 0 },
	{ 28,  58, 106,   0,  61,  88,  94,   -1,   2, 0 },
	{ 31,   0,  49,   0,  49, 300, 107,   -1,   2, 1 },
	{ 32,  57,  13,  57,  13,  95,  79,   22,   3, 0 },
	{ 32, 145,  63, 145,  63,  70,  46,   44,   3, 0 },
	{ 32, 215, 115, 215, 115,  87,  40,   -1,   3, 0 },
	{ 32,   0,  93,   0,  93, 124,  62,   -1,   3, 0 },
	{ 32, 236,  49, 318, 132,  56,  23,   -1,   3, 0 },
	{ 33,   0,  11,   0,  11, 104, 144,   -1,   3, 0 },
	{ 33, 182,  11, 182,  11, 138, 130,   70,   3, 0 },
	{ 34,   0,  13,   0,  13,  82, 142,   -1,   3, 0 },
	{ 41,   0,  25,   0,  25,  72, 129,   -1,   3, 0 },
	{ 41,  74,  24,  74,  24, 160,  95,   52,   3, 0 },
	{ 41, 236,  56, 236,  56,  84,  98,   -1,   3, 0 },
	{ 46, 152,  13, 152,  13, 168, 146,   -1,   3, 1 },
	{ 46,   0,  34,   0,  34,  64, 120,   -1,   4, 2 },
	{ 46, 117,  13, 139,  13, 136, 141,   -1,   6, 1 },
	{ 46, 267,  13, 267,  13,  53, 141,   -1,   7, 1 },
	{ 48, 170, 105, 170, 105,  82,  42,   -1,   8, 0 },
	{ 49,   0,  13,   0,  13, 320, 142,   -1,   8, 0 },
	{ 50,   0,  13,   0,  13,  68, 142,   -1,   8, 0 },
	{ 50, 144,  13, 144,  13,  96, 142,   -1,   8, 0 },
	{ 51,   0,  90,   0,  90, 218,  65,   79,   8, 0 },
	{ 51,   0,  25,   0, 113, 218,  42,   -1,   8, 0 },
	{ 51, 288, 103, 288, 103,  32,  41,   -1,   8, 0 },
	{ 52, 163,  41, 483,  41,  68,  98,   68,   8, 0 },
	{ 53,  88, 128,  88, 128, 232,  27,   -1,   8, 0 },
	{ 54,   0, 114,   0, 114, 320,  42,   -1,   8, 0 },
	{ 56,  26,  92,  26,  92,  94,  50,   68,   8, 0 },
	{ 57,   0, 155,   0, 110, 320,  45,   -1,   8, 0 },
	{ 57,   0,  49, 320,  91,  82,  64,   -1,   8, 0 },
	{ 57, 108,   0, 402,  42,  38, 113,   -1,   8, 0 },
	{ 58,   0,   6, 320,  13, 204, 119,   66,   8, 0 },
};

const OcclusionRect *occlusionRects(int room, uint &count) {
	count = 0;
	if (room <= 0)
		return nullptr;

	uint first = ARRAYSIZE(kOcclusionRects);
	for (uint i = 0; i < ARRAYSIZE(kOcclusionRects); i++) {
		if (kOcclusionRects[i].room != room)
			continue;
		if (first == ARRAYSIZE(kOcclusionRects))
			first = i;
		count++;
	}

	return count ? &kOcclusionRects[first] : nullptr;
}

const ScriptCond *occlusionGuards(const OcclusionRect &rect, uint &count) {
	count = rect.guardCount;
	return count ? &kOcclusionGuards[rect.firstGuard] : nullptr;
}

uint occlusionRectCount() {
	return ARRAYSIZE(kOcclusionRects);
}

} // End of namespace Alien
