/* ScummVM - Graphic Adventure Engine
 *
 * ScummVM is the legal property of its developers, whose names
 * are too numerous to list here. Please refer to the COPYRIGHT
 * file distributed with this source distribution.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

// Generated by tools/gen_plates.py of the Alien Incident reverse engineering
// repository -- do not edit by hand.
//
// What a room stamps into its background page as it opens: 96 steps across
// 26 rooms, lifted from the per-room plate routines in segment 10c9.

#include "alien/plates.h"

namespace Alien {

// The flag guards a step sits under, in step order.
static const ScriptCond kPlateGuards[] = {
	{ 0xa6de,   0, false, 0 },
	{ 0xa6d9,   0, false, 0 },
	{ 0xa6d9,   0, false, 0 },
	{ 0xa6fd,   1, false, 0 },
	{ 0xa6d9,   0, false, 0 },
	{ 0xa6e1,   1, false, 0 },
	{ 0xa6dc,   0, false, 0 },
	{ 0xa6dc,   0, false, 0 },
	{ 0xa6e0,   0, false, 0 },
	{ 0xa6dc,   0, false, 0 },
	{ 0xa6e2,   1, false, 0 },
	{ 0xa6e3,   1, false, 0 },
	{ 0xa6e4,   0, false, 0 },
	{ 0xa6e6,   0, false, 0 },
	{ 0xa6e5,   0, false, 0 },
	{ 0xa6fa,   1, false, 0 },
	{ 0xa6fe,   0, false, 0 },
	{ 0xa6fa,   1, false, 0 },
	{ 0xa6f9,   0, false, 0 },
	{ 0xa6f8,   1, false, 0 },
	{ 0xa6fa,   1, false, 0 },
	{ 0xa6f9,   0, false, 0 },
	{ 0xa6f8,   0, false, 0 },
	{ 0xa6fa,   1, false, 0 },
	{ 0xa6f6,   0, false, 0 },
	{ 0xa6f5,   1, false, 0 },
	{ 0xa6fa,   1, false, 0 },
	{ 0xa6f6,   0, false, 0 },
	{ 0xa6f5,   0, false, 0 },
	{ 0xa6fa,   1, false, 0 },
	{ 0xa6f4,   0, false, 0 },
	{ 0xa6fa,   1, false, 0 },
	{ 0xa70e,   1, false, 0 },
	{ 0xa70e,   1, false, 0 },
	{ 0xa70f,   0, false, 0 },
	{ 0xa70e,   1, false, 0 },
	{ 0xa6eb,   0, false, 0 },
	{ 0xa6ed,   0, false, 0 },
	{ 0x33a8,   0, false, 0 },
	{ 0xa6e9,   1, false, 0 },
	{ 0xa6ea,   0, false, 0 },
	{ 0xa6e9,   0, false, 0 },
	{ 0xa6ea,   1, false, 0 },
	{ 0xa6e9,   1, false, 0 },
	{ 0xa6ea,   1, false, 0 },
	{ 0xa6e8,   0, false, 0 },
	{ 0xa723,   1, false, 0 },
	{ 0xa720,   1, false, 0 },
	{ 0xa724,   0, false, 0 },
	{ 0xa726,   0, false, 0 },
	{ 0xa725,   1, false, 0 },
	{ 0xa6ee,   1, false, 0 },
	{ 0xa6f0,   1, false, 0 },
	{ 0xa739,   0, false, 0 },
	{ 0xa763,   0, false, 0 },
	{ 0x33ae,   1, false, 0 },
	{ 0x33ae,   1, false, 0 },
	{ 0x33ae,   1, false, 0 },
	{ 0x33ae,   1, false, 0 },
	{ 0x33ae,   1, false, 0 },
	{ 0x33ae,   1, false, 0 },
	{ 0xa719,   0, false, 0 },
	{ 0xa719,   0, false, 0 },
	{ 0xa715,   1, false, 0 },
	{ 0xa719,   0, false, 0 },
	{ 0xa716,   0, false, 0 },
	{ 0xa71a,   0, false, 0 },
	{ 0xa75a,   0, false, 0 },
	{ 0xa758,   0, false, 0 },
	{ 0xa758,   0, false, 0 },
	{ 0xa759,   1, false, 0 },
	{ 0xa758,   0, false, 0 },
	{ 0xa729,   1, false, 0 },
	{ 0x33b4,   0, false, 0 },
	{ 0x33b3,   1, false, 0 },
	{ 0xa752,   3, false, 0 },
	{ 0xa753,   0, false, 0 },
	{ 0xa753,   0, false, 0 },
	{ 0xa754,   1, false, 0 },
	{ 0xa753,   0, false, 0 },
	{ 0xa760,   1, false, 0 },
	{ 0xa760,   1, false, 0 },
	{ 0xa75e,   1, false, 0 },
	{ 0xa761,   1, false, 0 },
	{ 0xa75f,   1, false, 0 },
	{ 0xa75f,   1, false, 0 },
	{ 0xa75f,   1, false, 0 },
	{ 0xa777,   1, false, 0 },
	{ 0xa776,   0, false, 0 },
	{ 0x33be,   1, false, 0 },
	{ 0x33be,   1, false, 0 },
	{ 0x33c0,   0, false, 0 },
	{ 0x33c0,   1, false, 0 },
	{ 0xa780,   1, false, 0 },
	{ 0xa781,   0, false, 0 },
	{ 0xa77c,  18, false, 0 },
	{ 0xa77e,   0, false, 0 },
	{ 0xa77c,  18, false, 0 },
	{ 0xa77e,   0, false, 0 },
	{ 0xa77c,  18, false, 0 },
	{ 0xa77e,   0, false, 0 },
	{ 0xa786,   0, false, 0 },
	{ 0xa790,   0, false, 0 },
	{ 0xa798,   0, false, 0 },
	{ 0xa789,   0, false, 0 },
	{ 0xa7a6,   2, false, 0 },
	{ 0xa7a7,   1, false, 0 },
	{ 0xa7ab,   1, false, 0 },
	{ 0xa7b2,   0, false, 0 },
	{ 0xa7b9,   1, false, 0 },
	{ 0xa7d1,   0, false, 0 },
};

// Every step, grouped by room and in the order the room's plate routine runs them.
static const PlateStep kPlateSteps[] = {
	{  3, kPlateStamp, {   1,   1,   0,   0,   0 },   0, 1 },	// stamp slot 1 frame 1 when [0xa6de] == 0
	{  3, kPlateSel,   {   2,   0,   0,   0,   0 },   1, 1 },	// sel 2 when [0xa6d9] == 0
	{  3, kPlateSel,   {   3,   0,   0,   0,   0 },   2, 2 },	// sel 3 when [0xa6d9] == 0 when [0xa6fd] == 1
	{  3, kPlateStamp, {   3, 255,   0,   0,   0 },   4, 1 },	// stamp slot 3 frame sel when [0xa6d9] == 0
	{  3, kPlateStamp, {   4,   2,   0,   0,   0 },   5, 1 },	// stamp slot 4 frame 2 when [0xa6e1] == 1
	{  3, kPlateSel,   {   1,   0,   0,   0,   0 },   6, 1 },	// sel 1 when [0xa6dc] == 0
	{  3, kPlateSel,   {   2,   0,   0,   0,   0 },   7, 2 },	// sel 2 when [0xa6dc] == 0 when [0xa6e0] == 0
	{  3, kPlatePlay,  {   0, 255,   1,   0,   1 },   9, 1 },	// play slot 0 first sel count 1 rate 0 mode 1 when [0xa6dc] == 0
	{  6, kPlateStamp, {   0,  12,   0,   0,   0 },  10, 1 },	// stamp slot 0 frame 12 when [0xa6e2] == 1
	{  6, kPlateStamp, {   4,   1,   0,   0,   0 },  11, 1 },	// stamp slot 4 frame 1 when [0xa6e3] == 1
	{  6, kPlateStamp, {   1,   3,   0,   0,   0 },  12, 1 },	// stamp slot 1 frame 3 when [0xa6e4] == 0
	{  6, kPlateStamp, {   2,   6,   0,   0,   0 },  13, 1 },	// stamp slot 2 frame 6 when [0xa6e6] == 0
	{  6, kPlateStamp, {   3,   6,   0,   0,   0 },  14, 1 },	// stamp slot 3 frame 6 when [0xa6e5] == 0
	{  7, kPlateStamp, {   3,   6,   0,   0,   0 },  15, 2 },	// stamp slot 3 frame 6 when [0xa6fa] == 1 when [0xa6fe] == 0
	{  7, kPlateStamp, {   0,   2,   0,   0,   0 },  17, 3 },	// stamp slot 0 frame 2 when [0xa6fa] == 1 when [0xa6f9] == 0 when [0xa6f8] == 1
	{  7, kPlateStamp, {   0,   3,   0,   0,   0 },  20, 3 },	// stamp slot 0 frame 3 when [0xa6fa] == 1 when [0xa6f9] == 0 when [0xa6f8] == 0
	{  7, kPlateStamp, {   2,   3,   0,   0,   0 },  23, 3 },	// stamp slot 2 frame 3 when [0xa6fa] == 1 when [0xa6f6] == 0 when [0xa6f5] == 1
	{  7, kPlateStamp, {   2,   2,   0,   0,   0 },  26, 3 },	// stamp slot 2 frame 2 when [0xa6fa] == 1 when [0xa6f6] == 0 when [0xa6f5] == 0
	{  7, kPlateStamp, {   1,   1,   0,   0,   0 },  29, 2 },	// stamp slot 1 frame 1 when [0xa6fa] == 1 when [0xa6f4] == 0
	{  7, kPlatePlay,  {   4,   1,   7,   4,   1 },  31, 1 },	// play slot 4 first 1 count 7 rate 4 mode 1 when [0xa6fa] == 1
	{  8, kPlateSel,   {  12,   0,   0,   0,   0 },  32, 1 },	// sel 12 when [0xa70e] == 1
	{  8, kPlateSel,   {  13,   0,   0,   0,   0 },  33, 2 },	// sel 13 when [0xa70e] == 1 when [0xa70f] == 0
	{  8, kPlateStamp, {   3, 255,   0,   0,   0 },  35, 1 },	// stamp slot 3 frame sel when [0xa70e] == 1
	{ 10, kPlateStamp, {   4,   2,   0,   0,   0 },  36, 1 },	// stamp slot 4 frame 2 when [0xa6eb] == 0
	{ 10, kPlateStamp, {   6,   2,   0,   0,   0 },  37, 1 },	// stamp slot 6 frame 2 when [0xa6ed] == 0
	{ 10, kPlateStamp, {   7,   2,   0,   0,   0 },  38, 1 },	// stamp slot 7 frame 2 when [0x33a8] == 0
	{ 10, kPlateSel,   {   0,   0,   0,   0,   0 },  39, 0 },	// sel 0
	{ 10, kPlateSel,   {   1,   0,   0,   0,   0 },  39, 2 },	// sel 1 when [0xa6e9] == 1 when [0xa6ea] == 0
	{ 10, kPlateSel,   {   2,   0,   0,   0,   0 },  41, 2 },	// sel 2 when [0xa6e9] == 0 when [0xa6ea] == 1
	{ 10, kPlateSel,   {   3,   0,   0,   0,   0 },  43, 2 },	// sel 3 when [0xa6e9] == 1 when [0xa6ea] == 1
	{ 10, kPlateStamp, { 255,   6,   0,   0,   0 },  45, 1 },	// stamp slot sel frame 6 when [0xa6e8] == 0
	{ 11, kPlateStamp, {   0,   1,   0,   0,   0 },  46, 1 },	// stamp slot 0 frame 1 when [0xa723] == 1
	{ 11, kPlateStamp, {   1,   1,   0,   0,   0 },  47, 1 },	// stamp slot 1 frame 1 when [0xa720] == 1
	{ 11, kPlateStamp, {   4,   1,   0,   0,   0 },  48, 1 },	// stamp slot 4 frame 1 when [0xa724] == 0
	{ 11, kPlateStamp, {   5,   1,   0,   0,   0 },  49, 1 },	// stamp slot 5 frame 1 when [0xa726] == 0
	{ 11, kPlatePlay,  {   2,   1,   6,   1,   1 },  50, 1 },	// play slot 2 first 1 count 6 rate 1 mode 1 when [0xa725] == 1
	{ 13, kPlateStamp, {   1,   9,   0,   0,   0 },  51, 1 },	// stamp slot 1 frame 9 when [0xa6ee] == 1
	{ 13, kPlateSel,   {   2,   0,   0,   0,   0 },  52, 0 },	// sel 2
	{ 13, kPlateSel,   {   1,   0,   0,   0,   0 },  52, 1 },	// sel 1 when [0xa6f0] == 1
	{ 13, kPlateStamp, {   6, 255,   0,   0,   0 },  53, 0 },	// stamp slot 6 frame sel
	{ 15, kPlateStamp, {   2,   1,   0,   0,   0 },  53, 1 },	// stamp slot 2 frame 1 when [0xa739] == 0
	{ 17, kPlateStamp, {   0,   8,   0,   0,   0 },  54, 1 },	// stamp slot 0 frame 8 when [0xa763] == 0
	{ 18, kPlateMusic, {   7,   0,   0,   0,   0 },  55, 1 },	// music 7 when [0x33ae] == 1
	{ 18, kPlatePlay,  {   6,   1,   5,   2,   1 },  56, 1 },	// play slot 6 first 1 count 5 rate 2 mode 1 when [0x33ae] == 1
	{ 18, kPlateFlag,  { 42304,   1,   0,   0,   0 },  57, 1 },	// flag [0xa540] = 1 when [0x33ae] == 1
	{ 18, kPlatePlay,  {   7,   1,   5,   2,   1 },  58, 1 },	// play slot 7 first 1 count 5 rate 2 mode 1 when [0x33ae] == 1
	{ 18, kPlateFlag,  { 42305,   1,   0,   0,   0 },  59, 1 },	// flag [0xa541] = 1 when [0x33ae] == 1
	{ 18, kPlatePlay,  {   8,   1,   2,   0,   1 },  60, 1 },	// play slot 8 first 1 count 2 rate 0 mode 1 when [0x33ae] == 1
	{ 18, kPlateSel,   {   3,   0,   0,   0,   0 },  61, 1 },	// sel 3 when [0xa719] == 0
	{ 18, kPlateSel,   {   2,   0,   0,   0,   0 },  62, 2 },	// sel 2 when [0xa719] == 0 when [0xa715] == 1
	{ 18, kPlatePlay,  {   1, 255,   1,   0,   1 },  64, 1 },	// play slot 1 first sel count 1 rate 0 mode 1 when [0xa719] == 0
	{ 18, kPlatePlay,  {   2,   1,   1,   0,   1 },  65, 1 },	// play slot 2 first 1 count 1 rate 0 mode 1 when [0xa716] == 0
	{ 18, kPlatePlay,  {   5,   1,   1,   0,   1 },  66, 1 },	// play slot 5 first 1 count 1 rate 0 mode 1 when [0xa71a] == 0
	{ 19, kPlateStamp, {   5,   1,   0,   0,   0 },  67, 1 },	// stamp slot 5 frame 1 when [0xa75a] == 0
	{ 19, kPlateSel,   {   4,   0,   0,   0,   0 },  68, 1 },	// sel 4 when [0xa758] == 0
	{ 19, kPlateSel,   {   6,   0,   0,   0,   0 },  69, 2 },	// sel 6 when [0xa758] == 0 when [0xa759] == 1
	{ 19, kPlateStamp, {   0, 255,   0,   0,   0 },  71, 1 },	// stamp slot 0 frame sel when [0xa758] == 0
	{ 22, kPlateStamp, {   0,  38,   0,   0,   0 },  72, 1 },	// stamp slot 0 frame 38 when [0xa729] == 1
	{ 22, kPlateStamp, {   8,   1,   0,   0,   0 },  73, 1 },	// stamp slot 8 frame 1 when [0x33b4] == 0
	{ 22, kPlateStamp, {   9,   1,   0,   0,   0 },  74, 0 },	// stamp slot 9 frame 1
	{ 22, kPlateStamp, {   4,   1,   0,   0,   0 },  74, 1 },	// stamp slot 4 frame 1 when [0x33b3] == 1
	{ 26, kPlateStamp, {   0, 129,   0,   0,   0 },  75, 1 },	// stamp slot 0 frame 129 when [0xa752] == 3
	{ 26, kPlateSel,   {  16,   0,   0,   0,   0 },  76, 1 },	// sel 16 when [0xa753] == 0
	{ 26, kPlateSel,   {  15,   0,   0,   0,   0 },  77, 2 },	// sel 15 when [0xa753] == 0 when [0xa754] == 1
	{ 26, kPlateStamp, {   1, 255,   0,   0,   0 },  79, 1 },	// stamp slot 1 frame sel when [0xa753] == 0
	{ 28, kPlateSel,   {   1,   0,   0,   0,   0 },  80, 0 },	// sel 1
	{ 28, kPlateSel,   {  32,   0,   0,   0,   0 },  80, 1 },	// sel 32 when [0xa760] == 1
	{ 28, kPlateStamp, {   0, 255,   0,   0,   0 },  81, 0 },	// stamp slot 0 frame sel
	{ 28, kPlateSel,   {   1,   0,   0,   0,   0 },  81, 0 },	// sel 1
	{ 28, kPlateSel,   {   2,   0,   0,   0,   0 },  81, 1 },	// sel 2 when [0xa760] == 1
	{ 28, kPlateStamp, {   3, 255,   0,   0,   0 },  82, 0 },	// stamp slot 3 frame sel
	{ 28, kPlateStamp, {   4,   2,   0,   0,   0 },  82, 1 },	// stamp slot 4 frame 2 when [0xa75e] == 1
	{ 28, kPlateStamp, {   5,   2,   0,   0,   0 },  83, 1 },	// stamp slot 5 frame 2 when [0xa761] == 1
	{ 28, kPlateStamp, {   6,   1,   0,   0,   0 },  84, 1 },	// stamp slot 6 frame 1 when [0xa75f] == 1
	{ 28, kPlatePlay,  {   7,   1,  21,   1,   1 },  85, 1 },	// play slot 7 first 1 count 21 rate 1 mode 1 when [0xa75f] == 1
	{ 28, kPlateFlag,  { 42305,   1,   0,   0,   0 },  86, 1 },	// flag [0xa541] = 1 when [0xa75f] == 1
	{ 35, kPlateStamp, {   6,  29,   0,   0,   0 },  87, 1 },	// stamp slot 6 frame 29 when [0xa777] == 1
	{ 35, kPlateStamp, {   0,   2,   0,   0,   0 },  88, 1 },	// stamp slot 0 frame 2 when [0xa776] == 0
	{ 35, kPlateStamp, {   2,   1,   0,   0,   0 },  89, 1 },	// stamp slot 2 frame 1 when [0x33be] == 1
	{ 35, kPlatePlay,  {   3,   1,  31,   3,   1 },  90, 1 },	// play slot 3 first 1 count 31 rate 3 mode 1 when [0x33be] == 1
	{ 35, kPlateStamp, {   5,   1,   0,   0,   0 },  91, 1 },	// stamp slot 5 frame 1 when [0x33c0] == 0
	{ 35, kPlateStamp, {   5,   6,   0,   0,   0 },  92, 1 },	// stamp slot 5 frame 6 when [0x33c0] == 1
	{ 41, kPlateStamp, {   5,  40,   0,   0,   0 },  93, 1 },	// stamp slot 5 frame 40 when [0xa780] == 1
	{ 41, kPlateStamp, {   8,   4,   0,   0,   0 },  94, 1 },	// stamp slot 8 frame 4 when [0xa781] == 0
	{ 43, kPlateStamp, {   2,   1,   0,   0,   0 },  95, 2 },	// stamp slot 2 frame 1 when [0xa77c] == 18 when [0xa77e] == 0
	{ 44, kPlateStamp, {   2,   1,   0,   0,   0 },  97, 2 },	// stamp slot 2 frame 1 when [0xa77c] == 18 when [0xa77e] == 0
	{ 45, kPlateStamp, {   2,   1,   0,   0,   0 },  99, 2 },	// stamp slot 2 frame 1 when [0xa77c] == 18 when [0xa77e] == 0
	{ 46, kPlateStamp, {   1,   6,   0,   0,   0 }, 101, 1 },	// stamp slot 1 frame 6 when [0xa786] == 0
	{ 48, kPlateStamp, {   1,   5,   0,   0,   0 }, 102, 1 },	// stamp slot 1 frame 5 when [0xa790] == 0
	{ 49, kPlateStamp, {   4,   1,   0,   0,   0 }, 103, 1 },	// stamp slot 4 frame 1 when [0xa798] == 0
	{ 50, kPlateStamp, {   1,  28,   0,   0,   0 }, 104, 1 },	// stamp slot 1 frame 28 when [0xa789] == 0
	{ 56, kPlateStamp, {   2,   1,   0,   0,   0 }, 105, 2 },	// stamp slot 2 frame 1 when [0xa7a6] == 2 when [0xa7a7] == 1
	{ 58, kPlatePlay,  {   5,   4,   3,   6,   1 }, 107, 1 },	// play slot 5 first 4 count 3 rate 6 mode 1 when [0xa7ab] == 1
	{ 58, kPlatePlay,  {   2,   1,   1,   0,   2 }, 108, 1 },	// play slot 2 first 1 count 1 rate 0 mode 2 when [0xa7b2] == 0
	{ 58, kPlatePlay,  {   6,   1,   1,   0,   2 }, 109, 1 },	// play slot 6 first 1 count 1 rate 0 mode 2 when [0xa7b9] == 1
	{ 59, kPlateStamp, {   6,  22,   0,   0,   0 }, 110, 1 },	// stamp slot 6 frame 22 when [0xa7d1] == 0
};

const PlateStep *plateSteps(int room, uint &count) {
	count = 0;
	if (room <= 0)
		return nullptr;

	uint first = ARRAYSIZE(kPlateSteps);
	for (uint i = 0; i < ARRAYSIZE(kPlateSteps); i++) {
		if (kPlateSteps[i].room != room)
			continue;
		if (first == ARRAYSIZE(kPlateSteps))
			first = i;
		count++;
	}

	return count ? &kPlateSteps[first] : nullptr;
}

const ScriptCond *plateGuards(const PlateStep &step, uint &count) {
	count = step.guardCount;
	return count ? &kPlateGuards[step.firstGuard] : nullptr;
}

uint plateStepCount() {
	return ARRAYSIZE(kPlateSteps);
}

} // End of namespace Alien
