/* ScummVM - Graphic Adventure Engine
 *
 * ScummVM is the legal property of its developers, whose names
 * are too numerous to list here. Please refer to the COPYRIGHT
 * file distributed with this source distribution.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

// Generated by tools/gen_roominit.py of the Alien Incident reverse engineering
// repository -- do not edit by hand.
//
// The frame every animation slot opens on, as the room's own enter routine sets
// it: the effects it runs, with the puzzle-state guards they sit under.
//
//   127 plays over 31 rooms.

#include "alien/roominit.h"

namespace Alien {

static const ScriptEffect kRoomInit[] = {
	{ kOpAnimPlay1,      4, {     2,     1,     4,     9,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(2, 1, 4, 9)
	{ kOpMusic,          1, {     2,     0,     0,     0,     0,     0 }, 0x00, 1, { { 0xa6fa, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// music_play_slot(2)
	{ kOpAnimPlay1,      4, {     8,     1,    39,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(8, 1, 39, 3)
	{ kOpAnimPlay1,      4, {     5,     1,    13,     3,     0,     0 }, 0x00, 1, { { 0xa6f0, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(5, 1, 13, 3)
	{ kOpAnimPlay1,      4, {     7,     1,     7,     3,     0,     0 }, 0x00, 1, { { 0xa6f0, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(7, 1, 7, 3)
	{ kOpAnimPlay1,      4, {     0,     1,    11,     2,     0,     0 }, 0x00, 1, { { 0xa880, 7, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 1, 11, 2)
	{ kOpAnimPlay1,      4, {     0,    11,     1,     0,     0,     0 }, 0x00, 1, { { 0xa880, 7, true }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 11, 1, 0)
	{ kOpAnimPlay2,      4, {     1,    11,     1,     0,     0,     0 }, 0x00, 1, { { 0xa713, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(1, 11, 1, 0)
	{ kOpAnimPlay1,      4, {     1,     1,    25,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(1, 1, 25, 2)
	{ kOpAnimPlay1,      4, {     4,     1,    64,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(4, 1, 64, 2)
	{ kOpMusic,          1, {     7,     0,     0,     0,     0,     0 }, 0x00, 1, { { 0x33ae, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// music_play_slot(7)
	{ kOpAnimPlay1,      4, {     6,     1,     5,     2,     0,     0 }, 0x00, 1, { { 0x33ae, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(6, 1, 5, 2)
	{ kOpAnimPlay1,      4, {     7,     1,     5,     2,     0,     0 }, 0x00, 1, { { 0x33ae, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(7, 1, 5, 2)
	{ kOpAnimPlay1,      4, {     8,     1,     2,     0,     0,     0 }, 0x00, 1, { { 0x33ae, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(8, 1, 2, 0)
	{ kOpAnimPlay1,      4, {     4,     1,    17,     2,     0,     0 }, 0x00, 2, { { 0xa49f, 100, false }, { 0xa49c, 15, false }, { 0, 0, false } } },	// anim_play_mode1(4, 1, 17, 2)
	{ kOpAnimPlay1,      4, {     0,    26,    13,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 26, 13, 3)
	{ kOpAnimPlay1,      4, {     5,     1,    27,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(5, 1, 27, 2)
	{ kOpAnimPlay1,      4, {     3,     1,    14,     3,     0,     0 }, 0x00, 1, { { 0x98fe, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(3, 1, 14, 3)
	{ kOpAnimPlay1,      4, {     5,     1,    27,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(5, 1, 27, 2)
	{ kOpAnimPlay1,      4, {     6,     1,    11,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(6, 1, 11, 3)
	{ kOpAnimPlay1,      4, {     1,     1,     1,     0,     0,     0 }, 0x00, 1, { { 0x33b8, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(1, 1, 1, 0)
	{ kOpAnimPlay1,      4, {     4,     1,     5,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(4, 1, 5, 3)
	{ kOpAnimPlay1,      4, {     5,     1,     3,    15,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(5, 1, 3, 15)
	{ kOpAnimPlay1,      4, {     0,    24,   106,     3,     0,     0 }, 0x00, 1, { { 0xa49f, 35, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 24, 106, 3)
	{ kOpAnimPlay1,      4, {     2,     1,    10,     4,     0,     0 }, 0x00, 2, { { 0xa49f, 36, false }, { 0xa4ea, 0, false }, { 0, 0, false } } },	// anim_play_mode1(2, 1, 10, 4)
	{ kOpAnimPlay1,      4, {     1,     1,    15,     3,     0,     0 }, 0x00, 2, { { 0xa49f, 40, false }, { 0xad1c, 1, false }, { 0, 0, false } } },	// anim_play_mode1(1, 1, 15, 3)
	{ kOpAnimPlay1,      4, {     1,     1,    17,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(1, 1, 17, 3)
	{ kOpAnimPlay1,      4, {     5,     1,    11,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(5, 1, 11, 3)
	{ kOpAnimPlay1,      4, {     6,     1,    11,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(6, 1, 11, 3)
	{ kOpAnimPlay1,      4, {     7,     1,    11,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(7, 1, 11, 3)
	{ kOpAnimPlay1,      4, {     0,     1,    11,     3,     0,     0 }, 0x00, 1, { { 0xa72e, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 1, 11, 3)
	{ kOpAnimPlay1,      4, {     2,     1,     9,     3,     0,     0 }, 0x00, 1, { { 0xa72e, 1, true }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(2, 1, 9, 3)
	{ kOpAnimPlay1,      4, {     4,     1,     3,     0,     0,     0 }, 0x00, 1, { { 0xad1c, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(4, 1, 3, 0)
	{ kOpAnimPlay1,      4, {     4,     1,     3,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(4, 1, 3, 0)
	{ kOpAnimPlay1,      4, {     1,     1,    11,     3,     0,     0 }, 0x00, 1, { { 0xa4eb, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(1, 1, 11, 3)
	{ kOpAnimPlay1,      4, {     2,     1,     9,     3,     0,     0 }, 0x00, 1, { { 0xa4eb, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(2, 1, 9, 3)
	{ kOpAnimPlay1,      4, {     0,     1,    11,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 1, 11, 3)
	{ kOpAnimPlay1,      4, {     3,     1,    16,     3,     0,     0 }, 0x00, 3, { { 0x9908, 1, false }, { 0xa644, 1, false }, { 0xa72e, 0, false } } },	// anim_play_mode1(3, 1, 16, 3)
	{ kOpAnimPlay1,      4, {     0,     1,     1,    50,     0,     0 }, 0x00, 1, { { 0xa76d, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 1, 1, 50)
	{ kOpAnimPlay1,      4, {     1,     1,    33,     4,     0,     0 }, 0x00, 1, { { 0xa76c, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(1, 1, 33, 4)
	{ kOpAnimPlay1,      4, {     2,     1,    99,     4,     0,     0 }, 0x00, 1, { { 0x33bc, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(2, 1, 99, 4)
	{ kOpAnimPlay1,      4, {     0,     1,    11,     4,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 1, 11, 4)
	{ kOpAnimPlay1,      4, {     1,     1,    11,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(1, 1, 11, 3)
	{ kOpAnimPlay1,      4, {     2,     1,    11,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(2, 1, 11, 3)
	{ kOpAnimPlay1,      4, {     3,     1,    11,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(3, 1, 11, 3)
	{ kOpAnimPlay1,      4, {     4,     1,    31,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(4, 1, 31, 2)
	{ kOpAnimPlay1,      4, {    11,     1,    84,     4,     0,     0 }, 0x00, 1, { { 0xa880, 46, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(11, 1, 84, 4)
	{ kOpAnimPlay1,      4, {    10,     1,    64,     4,     0,     0 }, 0x00, 1, { { 0xad1c, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(10, 1, 64, 4)
	{ kOpAnimPlay1,      4, {     5,     1,    40,     4,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(5, 1, 40, 4)
	{ kOpAnimPlay1,      4, {     6,     1,    16,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(6, 1, 16, 2)
	{ kOpAnimPlay1,      4, {     0,     1,    15,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 1, 15, 2)
	{ kOpAnimPlay1,      4, {     0,    15,    30,     2,     0,     0 }, 0x00, 1, { { 0xa4ea, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 15, 30, 2)
	{ kOpAnimPlay1,      4, {     4,     1,    74,     2,     0,     0 }, 0x00, 1, { { 0xad3f, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(4, 1, 74, 2)
	{ kOpAnimPlay1,      4, {     0,    15,     1,     0,     0,     0 }, 0x00, 1, { { 0xa4ca, 15, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 15, 1, 0)
	{ kOpAnimPlay1,      4, {     5,     1,    10,     2,     0,     0 }, 0x00, 1, { { 0xa4ca, 15, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(5, 1, 10, 2)
	{ kOpAnimPlay1,      4, {     6,     1,    16,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(6, 1, 16, 2)
	{ kOpAnimPlay1,      4, {     0,     1,    15,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 1, 15, 2)
	{ kOpAnimPlay1,      4, {     0,    15,    30,     2,     0,     0 }, 0x00, 1, { { 0xa4ea, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 15, 30, 2)
	{ kOpAnimPlay1,      4, {     4,     1,    74,     2,     0,     0 }, 0x00, 1, { { 0xad3f, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(4, 1, 74, 2)
	{ kOpAnimPlay1,      4, {     0,    15,     1,     0,     0,     0 }, 0x00, 1, { { 0xa4ca, 15, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 15, 1, 0)
	{ kOpAnimPlay1,      4, {     5,     1,    10,     2,     0,     0 }, 0x00, 1, { { 0xa4ca, 15, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(5, 1, 10, 2)
	{ kOpAnimPlay1,      4, {     6,     1,    16,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(6, 1, 16, 2)
	{ kOpAnimPlay1,      4, {     0,     1,    15,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 1, 15, 2)
	{ kOpAnimPlay1,      4, {     0,    15,    30,     2,     0,     0 }, 0x00, 1, { { 0xa4ea, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 15, 30, 2)
	{ kOpAnimPlay1,      4, {     4,     1,    74,     2,     0,     0 }, 0x00, 1, { { 0xad3f, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(4, 1, 74, 2)
	{ kOpAnimPlay1,      4, {     0,    15,     1,     0,     0,     0 }, 0x00, 1, { { 0xa4ca, 15, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 15, 1, 0)
	{ kOpAnimPlay1,      4, {     5,     1,    10,     2,     0,     0 }, 0x00, 1, { { 0xa4ca, 15, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(5, 1, 10, 2)
	{ kOpAnimPlay1,      4, {     0,     1,    33,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 1, 33, 2)
	{ kOpAnimPlay1,      4, {     0,     1,    11,     1,     0,     0 }, 0x00, 1, { { 0xa789, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 1, 11, 1)
	{ kOpAnimPlay1,      4, {     1,     1,     6,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(1, 1, 6, 3)
	{ kOpAnimPlay1,      4, {     0,     1,     9,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 1, 9, 3)
	{ kOpAnimPlay1,      4, {     2,     1, 65450,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(2, 1, -86, 2)
	{ kOpAnimPlay1,      4, {     4,     1,    29,     3,     0,     0 }, 0x00, 1, { { 0xa880, 46, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(4, 1, 29, 3)
	{ kOpAnimPlay1,      4, {     1,     1,     3,     3,     0,     0 }, 0x00, 1, { { 0xa798, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(1, 1, 3, 3)
	{ kOpAnimPlay1,      4, {     2,     1,     8,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(2, 1, 8, 3)
	{ kOpAnimPlay1,      4, {     3,     1,    16,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(3, 1, 16, 3)
	{ kOpAnimPlay1,      4, {     5,     1,    11,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(5, 1, 11, 2)
	{ kOpAnimPlay1,      4, {     0,     1,    18,     4,     0,     0 }, 0x00, 2, { { 0x9908, 1, false }, { 0xa644, 1, false }, { 0, 0, false } } },	// anim_play_mode1(0, 1, 18, 4)
	{ kOpAnimPlay1,      4, {     0,     1,    33,     1,     0,     0 }, 0x00, 1, { { 0xa798, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 1, 33, 1)
	{ kOpAnimPlay1,      4, {     2,     1,    35,     4,     0,     0 }, 0x00, 1, { { 0xa880, 49, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(2, 1, 35, 4)
	{ kOpAnimPlay1,      4, {     5,     1,     3,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(5, 1, 3, 3)
	{ kOpAnimPlay1,      4, {     3,    22,     1,     0,     0,     0 }, 0x00, 1, { { 0xa880, 58, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(3, 22, 1, 0)
	{ kOpAnimPlay1,      4, {     4,    10,     1,     0,     0,     0 }, 0x00, 1, { { 0xa7a1, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(4, 10, 1, 0)
	{ kOpAnimPlay1,      4, {     0,     1,   126,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 1, 126, 3)
	{ kOpAnimPlay1,      4, {     4,     1, 65430,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(4, 1, -106, 3)
	{ kOpAnimPlay1,      4, {     1,     7,     1,     0,     0,     0 }, 0x00, 1, { { 0xa880, 55, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(1, 7, 1, 0)
	{ kOpAnimPlay1,      4, {     2,    10,     1,     0,     0,     0 }, 0x00, 2, { { 0xa880, 56, false }, { 0x33e2, 0, false }, { 0, 0, false } } },	// anim_play_mode1(2, 10, 1, 0)
	{ kOpAnimPlay1,      4, {     5,     1,     1,     0,     0,     0 }, 0x00, 1, { { 0x33e3, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(5, 1, 1, 0)
	{ kOpAnimPlay1,      4, {     6,     1,    40,     2,     0,     0 }, 0x00, 1, { { 0x33e3, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(6, 1, 40, 2)
	{ kOpAnimPlay1,      4, {    10,     1,    53,     4,     0,     0 }, 0x00, 1, { { 0x33f4, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(10, 1, 53, 4)
	{ kOpAnimPlay1,      4, {     1,     1,    29,     5,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(1, 1, 29, 5)
	{ kOpAnimPlay1,      4, {     2,     1,     5,     4,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(2, 1, 5, 4)
	{ kOpAnimPlay1,      4, {     0,    16,     1,     0,     0,     0 }, 0x00, 1, { { 0xa7a1, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 16, 1, 0)
	{ kOpAnimPlay1,      4, {     5,     1,    17,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(5, 1, 17, 2)
	{ kOpAnimPlay1,      4, {     9,     2,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(9, 2, 1, 0)
	{ kOpAnimPlay3,      4, {     6,    11,    11,     2,     0,     0 }, 0x00, 1, { { 0xa880, 60, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode3(6, 11, 11, 2)
	{ kOpAnimPlay1,      4, {     2,    17,     5,     4,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(2, 17, 5, 4)
	{ kOpAnimPlay1,      4, {     6,     1,    11,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(6, 1, 11, 2)
	{ kOpAnimPlay1,      4, {    10,     4,    15,     3,     0,     0 }, 0x00, 1, { { 0xa4f4, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(10, 4, 15, 3)
	{ kOpAnimPlay1,      4, {     3,     1,     3,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(3, 1, 3, 2)
	{ kOpAnimPlay1,      4, {     4,     1,     3,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(4, 1, 3, 2)
	{ kOpAnimPlay1,      4, {     5,     1,     3,     2,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(5, 1, 3, 2)
	{ kOpAnimPlay1,      4, {     1,    11,     1,     0,     0,     0 }, 0x00, 1, { { 0xa7a1, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(1, 11, 1, 0)
	{ kOpAnimPlay1,      4, {     0,    11,     1,     0,     0,     0 }, 0x00, 1, { { 0xa880, 52, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 11, 1, 0)
	{ kOpAnimPlay1,      4, {     0,     1,    11,     1,     0,     0 }, 0x00, 1, { { 0xa7a2, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 1, 11, 1)
	{ kOpAnimPlay3,      4, {     0,    11,    11,     1,     0,     0 }, 0x00, 1, { { 0xa7a2, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode3(0, 11, 11, 1)
	{ kOpAnimPlay1,      4, {     1,     1,    11,     1,     0,     0 }, 0x00, 1, { { 0xa7a4, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(1, 1, 11, 1)
	{ kOpAnimPlay3,      4, {     1,    11,    11,     1,     0,     0 }, 0x00, 1, { { 0xa7a4, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode3(1, 11, 11, 1)
	{ kOpAnimPlay1,      4, {     5,     1,     6,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(5, 1, 6, 3)
	{ kOpAnimPlay1,      4, {     1,    10,     1,     0,     0,     0 }, 0x00, 1, { { 0xa880, 52, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(1, 10, 1, 0)
	{ kOpAnimPlay1,      4, {     1,     1,    10,     1,     0,     0 }, 0x00, 1, { { 0xa7a4, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(1, 1, 10, 1)
	{ kOpAnimPlay3,      4, {     1,    10,    10,     1,     0,     0 }, 0x00, 1, { { 0xa7a4, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode3(1, 10, 10, 1)
	{ kOpAnimPlay1,      4, {     6,     1,   116,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(6, 1, 116, 3)
	{ kOpAnimPlay1,      4, {    10,     1,    53,     4,     0,     0 }, 0x00, 1, { { 0x33f4, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(10, 1, 53, 4)
	{ kOpAnimPlay1,      4, {     1,     1,    29,     5,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(1, 1, 29, 5)
	{ kOpAnimPlay1,      4, {     2,     1,     5,     4,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(2, 1, 5, 4)
	{ kOpAnimPlay1,      4, {     0,    16,     1,     0,     0,     0 }, 0x00, 1, { { 0xa7a1, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 16, 1, 0)
	{ kOpAnimPlay1,      4, {     3,    22,     1,     0,     0,     0 }, 0x00, 1, { { 0xa880, 51, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(3, 22, 1, 0)
	{ kOpAnimPlay2,      4, {     2,     1,     1,     0,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(2, 1, 1, 0)
	{ kOpAnimPlay1,      4, {     4,     1,    16,     3,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(4, 1, 16, 3)
	{ kOpAnimPlay1,      4, {     5,     4,     3,     6,     0,     0 }, 0x00, 1, { { 0xa4ef, 2, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(5, 4, 3, 6)
	{ kOpAnimPlay1,      4, {     1,     1,    30,     2,     0,     0 }, 0x00, 1, { { 0xa7d2, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(1, 1, 30, 2)
	{ kOpAnimPlay1,      4, {     2,     1,     5,     4,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(2, 1, 5, 4)
	{ kOpAnimPlay1,      4, {     3,     1,     5,     4,     0,     0 }, 0x00, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(3, 1, 5, 4)
	{ kOpAnimPlay2,      4, {     4,     1,     1,     0,     0,     0 }, 0x00, 1, { { 0xa7d2, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode2(4, 1, 1, 0)
	{ kOpAnimPlay1,      4, {     6,    22,     1,     0,     0,     0 }, 0x00, 1, { { 0xa7d2, 1, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(6, 22, 1, 0)
	{ kOpAnimPlay1,      4, {     0,    10,     1,     0,     0,     0 }, 0x00, 1, { { 0xa880, 53, false }, { 0, 0, false }, { 0, 0, false } } },	// anim_play_mode1(0, 10, 1, 0)
};

// Room number, first effect, count. A room absent from this table opens every
// slot blank, which is right for the rooms whose plate already draws them.
struct RoomInitRoom {
	byte room;
	uint16 first;
	uint16 count;
};

static const RoomInitRoom kRoomInitRooms[] = {
	{  3,   0,  1 },
	{  7,   1,  1 },
	{ 10,   2,  1 },
	{ 13,   3,  4 },
	{ 15,   7,  1 },
	{ 17,   8,  1 },
	{ 18,   9,  5 },
	{ 19,  14,  1 },
	{ 22,  15,  5 },
	{ 23,  20,  1 },
	{ 26,  21,  5 },
	{ 30,  26,  1 },
	{ 32,  27, 11 },
	{ 33,  38,  3 },
	{ 41,  41,  8 },
	{ 43,  49,  6 },
	{ 44,  55,  6 },
	{ 45,  61,  6 },
	{ 46,  67,  3 },
	{ 48,  70,  3 },
	{ 49,  73,  5 },
	{ 50,  78,  2 },
	{ 51,  80,  3 },
	{ 52,  83,  6 },
	{ 53,  89,  4 },
	{ 54,  93,  6 },
	{ 55,  99,  9 },
	{ 56, 108,  5 },
	{ 57, 113,  4 },
	{ 58, 117,  4 },
	{ 59, 121,  6 },
};

const ScriptEffect *roomInitEffects(int room, uint &count) {
	count = 0;
	for (uint i = 0; i < ARRAYSIZE(kRoomInitRooms); i++) {
		if (kRoomInitRooms[i].room != room)
			continue;
		count = kRoomInitRooms[i].count;
		return &kRoomInit[kRoomInitRooms[i].first];
	}
	return nullptr;
}

} // End of namespace Alien
