/* ScummVM - Graphic Adventure Engine
 *
 * ScummVM is the legal property of its developers, whose names
 * are too numerous to list here. Please refer to the COPYRIGHT
 * file distributed with this source distribution.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

// Generated by tools/gen_transitions.py of the Alien Incident reverse
// engineering repository -- do not edit by hand.
//
// The main loop's event chain: the room being left, the submode its exit armed,
// and the room that pair leads to, in the order the original tests them.
//
//   118 links over 47 rooms, 4 of them under a puzzle-flag guard.

#include "alien/transitions.h"

namespace Alien {

static const Transition kTransitions[] = {
	{  2,   4, 15, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 2, submode 4 -> room 15
	{  8,   1,  6, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 8, submode 1 -> room 6 (written inline)
	{  7,   1,  6, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 7, submode 1 -> room 6 (written inline)
	{  9,   1,  6, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 9, submode 1 -> room 6
	{  6,   3, 15, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 6, submode 3 -> room 15
	{  3,   1, 15, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 3, submode 1 -> room 15
	{ 13,  10, 35, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 13, submode 10 -> room 35
	{  6,   4,  8, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 6, submode 4 -> room 8
	{  6,   2,  7, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 6, submode 2 -> room 7
	{ 10,   1, 15, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 10, submode 1 -> room 15
	{ 11,   1, 15, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 11, submode 1 -> room 15
	{ 15,   4, 11, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 15, submode 4 -> room 11
	{ 19,   1, 28, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 19, submode 1 -> room 28
	{ 19,   2, 17, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 19, submode 2 -> room 17
	{ 28,   1, 19, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 28, submode 1 -> room 19
	{ 28, 111, 28, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 28, submode 111 -> room 28
	{  7,   2, 13, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 7, submode 2 -> room 13
	{ 18,   1,  6, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 18, submode 1 -> room 6
	{  6,   1, 18, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 6, submode 1 -> room 18
	{ 26,   1, 21, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 26, submode 1 -> room 21
	{ 26, 111, 26, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 26, submode 111 -> room 26
	{ 21,   3, 26, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 21, submode 3 -> room 26
	{ 21,   4, 17, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 21, submode 4 -> room 17
	{ 17,   1, 19, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 17, submode 1 -> room 19
	{ 17,   2, 21, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 17, submode 2 -> room 21
	{ 23,   1, 22, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 23, submode 1 -> room 22
	{ 23,   2, 31, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 23, submode 2 -> room 31
	{ 31,   2, 23, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 31, submode 2 -> room 23
	{ 22,   2, 23, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 22, submode 2 -> room 23
	{ 22,   1, 21, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 22, submode 1 -> room 21
	{ 22, 111, 56, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 22, submode 111 -> room 56
	{ 56, 100, 22, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 56, submode 100 -> room 22
	{ 27,   1, 15, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 27, submode 1 -> room 15
	{ 14,   1, 27, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 14, submode 1 -> room 27
	{ 14,   2, 31, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 14, submode 2 -> room 31
	{ 31,   1, 14, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 31, submode 1 -> room 14
	{ 31,   3, 32, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 31, submode 3 -> room 32
	{ 32,   2, 31, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 32, submode 2 -> room 31
	{ 14,   3, 25, 1, { { 0xa773,   0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 14, submode 3 -> room 25
	{ 14,   3, 34, 1, { { 0xa773,   0, true  }, { 0, 0, false }, { 0, 0, false } } },	// room 14, submode 3 -> room 34
	{ 25,   1, 33, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 25, submode 1 -> room 33
	{ 34,   1, 33, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 34, submode 1 -> room 33
	{ 34,   2, 14, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 34, submode 2 -> room 14
	{ 25,  20, 33, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 25, submode 20 -> room 33
	{ 27,   2, 14, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 27, submode 2 -> room 14
	{ 24,   1, 32, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 24, submode 1 -> room 32
	{ 33,   1, 30, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 33, submode 1 -> room 30
	{ 30,   1, 33, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 30, submode 1 -> room 33
	{ 33,   2, 25, 1, { { 0xa773,   0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 33, submode 2 -> room 25
	{ 33,   2, 34, 1, { { 0xa773,   1, false }, { 0, 0, false }, { 0, 0, false } } },	// room 33, submode 2 -> room 34
	{ 25,   2, 14, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 25, submode 2 -> room 14
	{ 35,   1, 27, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 35, submode 1 -> room 27
	{ 27,   3, 35, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 27, submode 3 -> room 35
	{ 35,  20, 35, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 35, submode 20 -> room 35
	{ 15,   6, 27, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 15, submode 6 -> room 27
	{ 43,  10, 45, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 43, submode 10 -> room 45
	{ 45,   1, 32, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 45, submode 1 -> room 32
	{ 50,   1, 49, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 50, submode 1 -> room 49
	{ 49,   1, 50, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 49, submode 1 -> room 50
	{ 50,   2, 48, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 50, submode 2 -> room 48
	{ 48,   1, 50, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 48, submode 1 -> room 50
	{ 48,   2, 46, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 48, submode 2 -> room 46
	{ 46,   3, 48, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 46, submode 3 -> room 48
	{ 41,   1, 44, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 41, submode 1 -> room 44
	{ 41,   2, 44, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 41, submode 2 -> room 44
	{ 44,   1, 41, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 44, submode 1 -> room 41
	{ 44,   2, 41, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 44, submode 2 -> room 41
	{ 41,   3, 43, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 41, submode 3 -> room 43
	{ 43,   1, 41, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 43, submode 1 -> room 41
	{ 41,  10, 46, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 41, submode 10 -> room 46
	{ 46,  10, 41, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 46, submode 10 -> room 41
	{ 40,   1, 48, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 40, submode 1 -> room 48
	{ 48,   3, 40, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 48, submode 3 -> room 40
	{ 40,   2, 32, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 40, submode 2 -> room 32
	{ 32,   3, 40, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 32, submode 3 -> room 40
	{ 58, 100, 56, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 58, submode 100 -> room 56
	{ 58,   1, 51, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 58, submode 1 -> room 51
	{ 58,   5, 59, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 58, submode 5 -> room 59
	{ 54,   1, 57, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 54, submode 1 -> room 57
	{ 54,  50, 60, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 54, submode 50 -> room 60
	{ 57,   1, 54, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 57, submode 1 -> room 54
	{ 56,   1, 52, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 56, submode 1 -> room 52
	{ 56,  10, 56, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 56, submode 10 -> room 56
	{ 52,   1, 56, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 52, submode 1 -> room 56
	{ 52,   2, 55, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 52, submode 2 -> room 55
	{ 52, 111, 58, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 52, submode 111 -> room 58
	{ 55,   1, 52, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 55, submode 1 -> room 52
	{ 59,   1, 53, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 59, submode 1 -> room 53
	{ 57,  10, 57, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 57, submode 10 -> room 57
	{ 53,   2, 59, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 53, submode 2 -> room 59
	{ 54, 100, 54, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 54, submode 100 -> room 54
	{ 51,   1, 58, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 51, submode 1 -> room 58
	{ 60,   1, 54, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 60, submode 1 -> room 54
	{ 55, 101, 53, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 55, submode 101 -> room 53
	{ 55, 102, 57, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 55, submode 102 -> room 57
	{ 55, 103, 51, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 55, submode 103 -> room 51
	{ 55, 104, 55, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 55, submode 104 -> room 55
	{ 51, 101, 53, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 51, submode 101 -> room 53
	{ 51, 102, 57, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 51, submode 102 -> room 57
	{ 51, 103, 51, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 51, submode 103 -> room 51
	{ 51, 104, 55, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 51, submode 104 -> room 55
	{ 57, 101, 53, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 57, submode 101 -> room 53
	{ 57, 102, 57, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 57, submode 102 -> room 57
	{ 57, 103, 51, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 57, submode 103 -> room 51
	{ 57, 104, 55, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 57, submode 104 -> room 55
	{ 53, 101, 53, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 53, submode 101 -> room 53
	{ 53, 102, 57, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 53, submode 102 -> room 57
	{ 53, 103, 51, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 53, submode 103 -> room 51
	{ 53, 104, 55, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 53, submode 104 -> room 55
	{  3, 111,  3, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 3, submode 111 -> room 3
	{ 15, 111, 15, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 15, submode 111 -> room 15
	{ 13,   1,  7, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 13, submode 1 -> room 7 (written inline)
	{  7,   1,  6, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 7, submode 1 -> room 6
	{ 15,   2, 10, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 15, submode 2 -> room 10
	{ 15,   3,  6, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 15, submode 3 -> room 6
	{ 15,   1,  3, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 15, submode 1 -> room 3
	{ 22,   1, 21, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 22, submode 1 -> room 21
	{ 21,   1, 22, 0, { { 0, 0, false }, { 0, 0, false }, { 0, 0, false } } },	// room 21, submode 1 -> room 22
};

const Transition *transitionTable(uint &count) {
	count = ARRAYSIZE(kTransitions);
	return kTransitions;
}

} // End of namespace Alien
