/* ScummVM - Graphic Adventure Engine
 *
 * ScummVM is the legal property of its developers, whose names
 * are too numerous to list here. Please refer to the COPYRIGHT
 * file distributed with this source distribution.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

#ifndef ALIEN_WALKGEOM_H
#define ALIEN_WALKGEOM_H

#include "alien/roomscripts.h"

namespace Alien {

/**
 * Where a click sends the player character, and which way he faces there.
 *
 * This is entry 0 of a scene overlay, and it sits above the router in walk.h:
 * the router answers "how do I get to that point", this answers "which point".
 * The original runs it as straight-line code that overwrites two globals --
 * walk_pos_x/y at [0xa7e8] and the arrival facing at [0xa805] -- so the rows of
 * a room are evaluated in order and the last one that matches wins.
 *
 * Four things happen in there, in whatever order the room's author wrote them:
 *
 *  - the target starts as the click itself, with no turn (1021:0x3ea);
 *  - a rectangle may snap the target onto one of its own edges, which is how a
 *    room keeps the character off its furniture and on its floor line;
 *  - a rectangle may redirect the click somewhere else entirely, with a facing
 *    (`kWalkZone`) -- clicking the far side of a counter walks to its near side;
 *  - an object id may name its own approach point and facing (`kWalkObject`),
 *    which is what makes the character stand beside what he is about to use
 *    rather than on top of it.
 *
 * `kWalkSubmode` is the other half of the mechanism: it records that clicking
 * an object arms a game submode, and OBJ:0x53cd fires that submode once the
 * character has arrived within three pixels of the target and is facing the
 * recorded way. That is how a room exit works -- see docs/walk_system.md.
 *
 * Generated by tools/gen_walkgeom.py; see docs/overlay_entries.md.
 */
enum WalkGeomKind {
	kWalkSnapDown = 0,	///< inside the rect, move the target down to y2
	kWalkSnapUp,		///< ... up to y1
	kWalkSnapRight,		///< ... right to x2
	kWalkSnapLeft,		///< ... left to x1
	kWalkZone,			///< inside the rect, walk to (x, y) facing `facing`
	kWalkObject,		///< up to four object ids sharing one approach point
	kWalkMaxY,			///< a click below `a` walks to y instead
	kWalkMinY,			///< a click above `a` walks to y instead
	kWalkMaxX,			///< a click right of `a` walks to x instead
	kWalkMinX,			///< a click left of `a` walks to x instead
	kWalkSubmode		///< clicking object `a` arms submode `x` on arrival
};

/** No turn on arrival. The original's [0xa805] default, and anything over 4. */
enum { kWalkFacingKeep = 10 };

/**
 * One row of a room's walk geometry.
 *
 * `a` to `d` are the rectangle x1, y1, x2, y2 -- except for kWalkObject, where
 * they are up to four object ids with zero for the unused ones, kWalkMaxY,
 * kWalkMinY, kWalkMaxX and kWalkMinX, where `a` is the coordinate the click is
 * compared against, and
 * kWalkSubmode, where `a` is the object id and `x` the submode.
 */
struct WalkGeom {
	byte kind;
	int16 a, b, c, d;
	int16 x, y;
	byte facing;
	byte guardCount;
	ScriptCond guards[3];
};

/**
 * A room's rows in overlay order, or null with a count of zero. A room with no
 * overlay has no geometry and its clicks are walked to as they stand.
 */
const WalkGeom *walkGeomForRoom(int room, uint &count);

} // End of namespace Alien

#endif
